### ISSUE TITLE
Calculate minimal variant card width and give remaining to ranked variants table

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio.vue#113]

**Comment by AlistairNWard** [comment]
How does this minimal calculation work? If I look at PDHA1 for the demo data, there is only a single variant in the table, but it has a large width.

**Comment by tonydisera** [comment]
Uhm...  I kinda hacked it.  Right now, the code determines the minimum required width for the Variant detail card and gives the rest to the Ranked Variants panel.  

I agree, it should also consider the minimum width to show all Ranked Variants and give any excess back to the Variant Detail card.

**Comment by AlistairNWard** [comment]
I just opened the demo data, and this seems to have reverted back to how it used to be. Tried to close this from beneath my pedantic gaze...?
![Screen Shot 2018-08-01 at 9.51.13 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5750332babe50b1300c53bf6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6454f26b7191a371f1172a4f5e5c5edd3c4a4356bcbbd671f3e57862804e0ebc836e0b26926c47aebc821ee901ba228e4cd7e2b9de1ad2f42f67b6d5db1063474f4dcbed5727a29b41c95df548e04e54a1123561e2732431.png)

**Comment by AlistairNWard** [comment]
Although I've tried this a few times, and it isn't always repeatable. This is what I observe:

1. The data is loading.
2. The data for RAI1 comes in and the ranked variants table populates and everything is ok,
3. The remaining data comes available and the left panel opens. pushing the ranked variants table to the right, disappearing behind the gene summary (as in the image above).
4. Usually, the panel then resizes and everything is ok again, but somehow I have been able to stop the resize and end up as shown above.

**Comment by tonydisera** [comment]
Yeah, I'm seeing this too.  I'll try to fix this.

**Comment by tonydisera** [comment]
I can't seem to reproduce this bug this morning.  I did push some bug fixes, so I wonder if one of these errors was preventing the recalc of the Ranked Variants panel width.  Al, would you let me know if you see this bug again?  Thanks!

**Comment by tonydisera** [comment]
Funny!  I just reproduced it.  It seems related to switching tabs.  Yeah!

**Comment by tonydisera** [comment]
Fixed!  To reproduce, launch gene.iobio from hub and then switch back to the bub browser tab. Give it about ~5 seconds (enough for RAI1 to finish) and then switch back to gene.iobio browser tab.
