### ISSUE TITLE
Need strategy for loading +1000 variants in Variant Card 

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio.vue#120]

**Comment by tonydisera** [comment]
![Screen Shot 2018-07-12 at 7.57.21 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5759f0b40b37b00e00e7d3d4/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246455f16b7191a37ff1172c4f5d5e5ecc3c4a4356bcbbd671f3e57862804e0ebc836e0b26926c47aebc821ee901ba228e4cd7e2b9de1ad2f42f67b6d5db1063474f4dcbed5727a19041c95df54ae54952a51b3563e47f2431.png)
![Screen Shot 2018-07-12 at 7.58.23 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5759f0b40b37b00e00e7d3d4/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246455f16b7191a37ff117234f5d5c5ecc3c4a4356bcbbd671f3e57862804e0ebc836e0b26926c47aebc821ee901ba228e4cd7e2b9de1ad2f42f67b6d5db1063474f4dcbed5727a19041c95df54ae54952a51b3165e2732431.png)

**Comment by tonydisera** [comment]
The problem is that there are simply too many genes to display (+5000).  Need a way to check count up front and only show variants based on some kind of filter or perhaps use strategy employed with ClinVar variants where we a histogram of counts across gene coordinates.  In gene.iobio 2.0, I think we only displayed coding variants, but for WGS, it seems like this would not be an appropriate filter.

**Comment by mvelinder** [comment]
Not relevant anymore
