### ISSUE TITLE
Left panel doesn't automatically open

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio.vue#131]
I'm launching from hub (13529.p1) in gene ATP7B. A number of interesting variants are present, but the list at the left doesn't automatically open. I think this list is really powerful, so should probably default to being open.

**Comment by AlistairNWard** [comment]
Is this just a duplicate of #111?

**Comment by tonydisera** [comment]
Yep.  I'm going to close this one.  I'm impressed.  I never look over the issue list when I add one.
