### ISSUE TITLE
Flag variant behaviour

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio.vue#139]
I'm looking (again) at 13529.p1 family from SFARI in ATP7B.

1. Selecting/deselecting "Flag variant", "Remove flag" causes the data to be reloaded. Also, focus is lost from the selected variant, so while you still see the data pertaining to the variant, you can no longer see which variant is selected (either in the table or the proband card).

2. Should be put the flag as the last row in the table? It is a little confusing to flag a variant, everything is reloaded, and the table is resorted and the variant you flagged has now moved over to the left (as the flag is the highest variable in the ranking). This gives the impression that gene flagged the wrong variant.

3. The table isn't always refreshed, so you can remove a flag, but the flag remains. So you end up with a flagged variant that also has the option to be flagged (not unflagged). You can replicate as follows:

a) Open 13529.p1 family from SSC in ATP7B
b) Select variant 15. Flag it.
c) Select variant 15. Flag it. (Variant 15 is now new - see point 2).
d) Select variant 9 - should be flagged. Remove flag. Removed it is not.

<img width="1343" alt="screen shot 2018-07-19 at 9 19 02 am" src="https://user-images.githubusercontent.com/523111/42944870-cf2acae6-8b34-11e8-9fc6-09aa8b6636d7.png">

PeDante strikes again! I feel like this relates me to Dante. Are you implying that working with me is like a new circle of hell?

**Comment by tonydisera** [comment]
So, you like your moniker, huh?  I just thought added the e made you sound even more sophisticated.  Nice touch, huh?

I'm working on this bug right now.  I think I'm then one in the circle of hell, not you. ;-)

**Comment by AlistairNWard** [comment]
I don't think it's an unreasonable argument that the flags are important to sort on first. Disorienting is the right word! Looks to me like:

1. FIXED: After flagging a variant, focus on that variant is now retained.
2. The flag/unflag option works correctly.

3. The whole page still refreshes after flagging a variant. I don't know if this is possible, but if on flagging a variant, the variant cards did not reload, and as the table refreshed, moving the variant to its new position, we had a message pop up over the table stating that it was resorting, or something like that? I initially thought gene was flagging the wrong variant (I thought it just kept flagging the variant next to the red flagged variants) , so I think this will trip people up if they don't have something showing that the variant they just flagged moved. I don't know what would make sense, or is technically reasonable though!

**Comment by tonydisera** [comment]
You know what would be cool?  This matrix is actually a D3 chart, so I should be able to use transitions.  PeDANT strikes again!
