### ISSUE TITLE
Highlighting in proband card

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio.vue#140]
If I select a variant from the left list, the variant is highlighted in the table and the proband card. If I now select a variant from the ranked variants table, the previous variant is no longer highlighted in the table, but it persists in the proband card.

<img width="102" alt="screen shot 2018-07-19 at 9 20 49 am" src="https://user-images.githubusercontent.com/523111/42944960-1664c5d8-8b35-11e8-9647-6369896a4fe9.png">

**Comment by tonydisera** [comment]
Yikes.  That smells like a bug I introduced yesterday!

**Comment by AlistairNWard** [comment]
No, it was there before. I put too many things in an individual issue, so some things got lost. I'll try to do better at focused issues!

**Comment by tonydisera** [comment]
This is perfect for me!  I like the bug and fix slinging cycle!  Thank you for all of your help.

**Comment by AlistairNWard** [comment]
I enjoy working with the apps and trying to help. Hopefully there'll be a bit more time to do this over the summer!
