### ISSUE TITLE
Support cram file format for alignments

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio.vue#142]

**Comment by fgvieira** [comment]
Was this feature implemented?
If so, how can I load CRAM files? I have version 3.2.0.2, and it still says it needs BAM/BAI files...

**Comment by tonydisera** [comment]
Thanks for pointing this out Filipe.  Indeed, .cram and .crai local file support is not yet available in gene.iobio.  (It is supported if the .cram/.crai files are URLs).  We have plans to introduce local file support from .crams.  Please see a new issue #341.
