### ISSUE TITLE
Nav bar confusing for searching on gene or searching by phenotype to get gene list.

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio.vue#148]

**Comment by tonydisera** [comment]
When Marti Tristani use gene.iobio, he was confused by the gene with the + button in the nav bar.  He understood the + to mean 'Enter gene and phenotype'.  

So I changed the button to 'edit' and added 'OR' between the gene search and the phenotype search.

Al, does that make sense?

![Screen Shot 2018-07-27 at 4.08.15 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5759f0b40b37b00e00e7d3d4/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246456f46b7191a37cf112234f5e5a5ecc3c4a4356bcbbd671f3e57862804e0ebc836e0b26926c47aebc821ee901ba228e4cd7e2b9de1ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df549e64f5ca0133165e2722431.png)

**Comment by AlistairNWard** [comment]
Yes, this makes perfect sense to me.

**Comment by tonydisera** [comment]
Awesome!
