### ISSUE TITLE
MHL1 gene ACMG (Marti) showing 0% gnomAD AF, but Matt pull it up

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio.vue#154]

**Comment by tonydisera** [comment]
![image (1).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5759f0b40b37b00e00e7d3d4/125516c66e82c728ace21e0d46e1999b2487c3e1dea0fd0fe64de29b234324676b5ee17e7187b02cbd467a075d5b4ead17585f46f9fadb7fa3e26a62964e49bc8f3900299f7744eeaa880dbe08b0218e4c87b0be8c4ec8ef3a25e399c2.png)

**Comment by AlistairNWard** [comment]
Since we don't have a specific project attached to this, it will be difficult to check, but I am always 100% sure that this will be the same GRCh38 GnomAD issue that is being addressed elsewhere.
