### ISSUE TITLE
Add ability for user to interpret variant significance

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio.vue#169]

**Comment by tonydisera** [comment]
@AlistairNWard @mvelinder   Here is the preliminary feature for classifying variants.  This feature still needs refinement, but I wanted to get something out there for you guys to play with.  

You can try by launching:  http://clin.iobio.io  or http://dev.gene.iobio
![Screen Shot 2018-08-07 at 5.27.31 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5759f0b40b37b00e00e7d3d4/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6454f46b7191a37df1102c4f5c5e5ecc3c4a4356bcbbd671f3e57862804e0ebc836e0b26926c47aebc821ee901ba228e4cd7e2b9de1ad2f42f67b6d5db1063474f4dcbed5727a19041c95df548e74551a11a3563ef722431.png)
![Screen Shot 2018-08-07 at 5.27.40 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5759f0b40b37b00e00e7d3d4/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6454f46b7191a37df1102c4f5b5f5ecc3c4a4356bcbbd671f3e57862804e0ebc836e0b26926c47aebc821ee901ba228e4cd7e2b9de1ad2f42f67b6d5db1063474f4dcbed5727a19041c95df548e74551a2133560ef702431.png)

**Comment by AlistairNWard** [comment]
I like this. I definitely think this is as much as we need before putting in front of the clinicians.

My only comment is whether there is just too much information on screen now, and whether it might be worth simplifying. So for example, in the left list, do we really need to know the coordinates, alleles, rsid etc? I wonder if at this level, all we really need to know is that variant #1 falls under the Pathogenic/Likely pathogenic category and then have the symbols that highlight major attributes of the variant? A possible thought would then be that the list is super simple, with the gene and a few symbols and a clear button for reviewing. Then we could make the modal a bit more comprehensive, with details of the variant appearing at the top of the modal, and then the notes and interpretation available. Thoughts?

**Comment by tonydisera** [comment]
Funny.  I was concerned with the same design issue last night as well!  It is just to fucking much.  I like your idea of scaling back on the entries for flagged variants.  I've also been playing around with some other design ideas to make the UI less "heavy" and bring more attention to the important elements.

Here is something I was playing around with last night.  I pulled the cool font that @mvelinder is using in his new iobio website, removed header icons from the flagged variants, and made the nav bar white.

<img width="1432" alt="screen shot 2018-08-08 at 9 47 45 am" src="https://user-images.githubusercontent.com/8420103/43848578-77b68f9a-9af0-11e8-98a2-cfc2dae8d863.png">

**Comment by AlistairNWard** [comment]
I like it. Going a little further...

![Asset 1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5750332babe50b1300c53bf6/125516c66e82c728ace21e0d46c987892696c3f8cda5fd53b652fa912a5265296b51a2292381e12cbe4429555f5e18ac415a5a47aead8c7ff0a42062c80d55b98e30063e937f03a6aa8317b500bf23884881b5b58f48c5ee3437aa.png)

**Comment by tonydisera** [comment]
Yep, I think we might be converging on a better design!  I'm pretty stoked.

**Comment by tonydisera** [comment]
@mvelinder Your thoughts?

**Comment by tonydisera** [comment]
@AlistairNWard Better?  I kept AF and consequence, especially since we tend to set the AF filter pretty loosely.


![Screen Shot 2018-08-08 at 1.53.19 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5759f0b40b37b00e00e7d3d4/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6454fb6b7191a379f117284f5e565ecc3c4a4356bcbbd671f3e57862804e0ebc836e0b26926c47aebc821ee901ba228e4cd7e2b9de1ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df548e6485da4103260e2742431.png)

**Comment by AlistairNWard** [comment]
Yeah, those are probably worth keeping available at a glance. Definitely looks better IMO.
