### ISSUE TITLE
Gracefully handle case where gene not returned from geneinfo (no transcripts found)

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio.vue#170]

**Comment by tonydisera** [comment]
![Screen Shot 2018-08-08 at 3.15.04 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5759f0b40b37b00e00e7d3d4/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6454fb6b7191a37bf1132e4f5f5b5ecc3c4a4356bcbbd671f3e57862804e0ebc836e0b26926c47aebc821ee901ba228e4cd7e2b9de1ad2f42f67b6d5db1063474f4dcbed5727a19041c95df548e64b57ad173f6be3742431.png)

**Comment by tonydisera** [comment]
It turns out that this gene exists in RefSeq, but not Gencode.  So we should try to use the default gene source, but if the gene only exists in the non-selected gene source, grab the gene model (and transcripts) from it.

**Comment by mvelinder** [comment]
#502 should address this I think. I'm closing
