### ISSUE TITLE
Compound het should look at VEP impact on canonical only, not highest impact across all transcripts

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio.vue#180]

**Comment by AlistairNWard** [comment]
Why is that? It makes sense that we want to consider VEP impact of both variants in the compound het from the same transcript, but why would it need to be the canonical?

**Comment by tonydisera** [comment]
Agreed.

**Comment by mvelinder** [comment]
Seems we agree the current behavior is fine. I'm closing
