### ISSUE TITLE
Tighten preset filter for moderate/high impact variants

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio.vue#208]

**Comment by tonydisera** [comment]
Is the ‘Moderate or high impact’ preset filter in gene.iobio too permissive.  Often, the majority of variants passing this filter are moderate impact variants that are hets and have a benign/likely benign ClinVar designation.  This makes sense, given that these are variants that don’t pass the ‘Clinvar pathogenic’ or inheritance modes filters.  Arguably, a moderate or high impact variant may play some role in the proband’s syndrome/disorder/disease.  I just wonder if the criteria should be a bit more selective.

What are your thoughts on tightening this preset filter in the following way?

Show high impact (LOF) variants only.
Lower the allele frequency to < 1%
Exclude any variants with all benign/likely benign ClinVar designations unless there is a high REVEL score (or a predicted deleterious designation from SIFT or Polyphen)

**Comment by tonydisera** [comment]
Al - I think this is probably a good idea. We should really try and restrict the preset filters to highlight variants that have a real chance of being useful. If these turn up nothing, the user can relax filters on their own. Is it worth including a REVEL cutoff in the filter?

**Comment by tonydisera** [comment]
from Matt - I like this ideas. I think we'll just want to make sure we notify the user that these filters are applied and they can loosen them to bring more data in.

**Comment by tonydisera** [comment]
For now, we will just show high impact  variants with AF < 1%.  We will need to implement the other criteria after the workshop.

**Comment by mvelinder** [comment]
Done
