### ISSUE TITLE
Support new format on info fields in clinvar vcf

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio.vue#234]

**Comment by tonydisera** [comment]
Differences
CLNSIG=5; vs CLNSIG=Pathogenic; (code vs text)
CLNACC=RCV000132731.1 vs * missing * (missing)
CLNDBN=Smith-Magenis_syndrome; vs CLNDN=Smith-Magenis_syndrome; (different tag)

Latest clinvar
ALLELEID=152915;
CLNDISDB=MedGen:C0795864,OMIM:182290,Orphanet:ORPHA819,SNOMED_CT:401315004;
CLNDN=Smith-Magenis_syndrome;
CLNHGVS=NC_000017.10:g.17698535G>A;
CLNREVSTAT=no_assertion_criteria_provided;
CLNSIG=Pathogenic;
CLNVC=single_nucleotide_variant;
CLNVCSO=SO:0001483;
GENEINFO=RAI1:10743;
MC=SO:0001587|nonsense;
ORIGIN=32;
RS=527236033

Working (on production) clinvar
RS=527236033;
RSPOS=17698535;
dbSNPBuildID=141;
SSR=0;
SAO=3;
VP=0x050060000605000002110100;
GENEINFO=RAI1:10743;
WGT=1;
VC=SNV;
PM;
NSN;
REF;
ASP;
LSD;
OM;
CLNALLE=1;
CLNHGVS=NC_000017.10:g.17698535G>A;
CLNSRC=.;
CLNORIGIN=32;
CLNSRCID=.;
CLNSIG=5;
CLNDSDB=MedGen:OMIM:Orphanet:SNOMED_CT;
CLNDSDBID=C0795864:182290:ORPHA819:401315004;
CLNDBN=Smith-Magenis_syndrome;
CLNREVSTAT=no_criteria;
CLNACC=RCV000132731.1

**Comment by tonydisera** [comment]
Here is another example of the new version.  Notice that there are still | to delimit different conditions

ALLELEID=102081;
CLNDISDB=MedGen:CN169374|MedGen:CN517202;
CLNDN=not_specified|not_provided;
CLNHGVS=NC_000017.10:g.17700043_17700045delGAG;
CLNREVSTAT=criteria_provided,_conflicting_interpretations;
CLNSIG=Conflicting_interpretations_of_pathogenicity;
CLNSIGCONF=Benign(2),Likely_benign(3),Uncertain_significance(1);
CLNVC=Deletion;CLNVCSO=SO:0000159;
CLNVI=HGMD:CD116392;
GENEINFO=RAI1:10743;ORIGIN=1;RS=149716029

**Comment by tonydisera** [comment]
Model new vcf parsing after SampleModel._addClinvarEutilInfoToVariant

**Comment by tonydisera** [comment]
clinvar uuid needs to come from id column in vcf rec


take out temp vcf
code and
try with ftp vcf

**Comment by tonydisera** [comment]
Using VCF rather than EUTILS, results in clinvar entry when it looks like it is for another allele:
![Screen Shot 2018-10-29 at 7.46.13 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5759f0b40b37b00e00e7d3d4/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236456fa6b7191a37ff1162d4f5e5c5ecc3c4a4356bcbbd671f3e57862804e0ebc836e0b26926c47aebc821ee901ba228e4cd7e2b9de1ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df24be94b51a4163761e3702431.png)


![Screen Shot 2018-10-29 at 7.46.26 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5759f0b40b37b00e00e7d3d4/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236456fa6b7191a37ff1162d4f5d595ecc3c4a4356bcbbd671f3e57862804e0ebc836e0b26926c47aebc821ee901ba228e4cd7e2b9de1ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df24be94b51a415376ae7722431.png)

![Screen Shot 2018-10-29 at 7.46.04 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5759f0b40b37b00e00e7d3d4/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236456fa6b7191a37ff1162d4f5f5b5ecc3c4a4356bcbbd671f3e57862804e0ebc836e0b26926c47aebc821ee901ba228e4cd7e2b9de1ad2f42f67b6d5db1063474f4dcbed5727a29941c95df24be94b51a41a3261e0732431.png)

**Comment by tonydisera** [comment]
Hi Al.  I’m mystified by the coordinates in the clinvar entry: https://www.ncbi.nlm.nih.gov/clinvar/variation/96187/
ncbi.nlm.nih.gov
NM_030665.3(RAI1):c.3781_3783delGAG (p.Glu1261del) Simple - Variation Report - ClinVar - NCBI
ClinVar archives and aggregates information about relationships among variation and human health.
According to ClinVar, here are the GRCh37 coords - Chr17: 17700043 - 17700045 (on Assembly GRCh37)
But look at the ClinVar vcf:
17    17700037    96187    AAGG    A

Al [1:27 PM]
That’s less than ideal
I’m on the train, but I’ll take a look when I get in. Seems really odd

tonydisera [1:28 PM]
The starting position in the ClinVar vcf seems right to me.  17700037.  Why could the ClinVar web interface show at start position at 17700043?
Thanks.  I know you can help me unravel this.  I’m scratching my head…

Al [1:30 PM]
I’m not I’ll be able to help, but two sets of eyes are often better than one!!

Al [2:08 PM]
Ok, so this can be even more exciting
I looked on dbSNP
Screen Shot 2018-10-30 at 4.08.57 PM.png 

So there it is listed as 17700038. Different again
Ok, so here are some thoughts
This is the genome browser view of this region
Screen Shot 2018-10-30 at 4.14.37 PM.png 

So it looks to me that 17:17,700,037 is the first A at the left. The variant is a deletion of GAG, and the ClinVar variant you listed is deletion of AGG
So, I agree with you that 17:17,700,037 is the starting location for the deletion of AGG
But that ClinVar page is showing deletion of GAG
In a VCF, we would then set the coordinate to be the anchor base to the left of the GAG, so we should see a ref allele of GGAG going to G at position 17:17,700,039
But, ClinVar lists it at 17:17,700,043 and this actually makes sense to me
An annoying feature is that we always left align indels in a VCF. So, in this case, the sequence has GAG followed by GAG. So technically, it is equivalent to claim either the first or second GAG is repeated
For a VCF, we left align, so would delete the first GAG and list the coordinate as one base to the left of the first G
HGVS codes obviously, to maximise confusion, right align, so they would delete the last (e.g. second) repetition of GAG
This would mean bases 17:17,700,043 to 17:17,700,045 are deleted
As listed in ClinVar
This is super confusing
ClinVar points to dbSNP and this is the 1000G browser
https://www.ncbi.nlm.nih.gov/variation/tools/1000genomes/?gts=rs149716029
The highlighting shows the second GAG deleted, but in the table shows the allele as AAGG, consistent with the deletion of AGG
So there seems to be some real confusion surrounding what is actually deleted here

Al [2:50 PM]
@tonydisera

tonydisera [2:51 PM]
Hi!
Wow.  Thanks for the research!  I will try to digest your analysis.  Thank you.  This is very confusing.

Al [2:52 PM]
The key thing here which is super annoying is that VCF spec is left align and HGVS is right align
That means that when we have a deletion in a repeat region, when we convert to HGVS coordinates, we are guaranteed to be wrong

tonydisera [2:52 PM]
Oh!  I see.

Al [2:52 PM]
Which is awesome

tonydisera [2:53 PM]
What the hell.

Al [2:53 PM]
I know. Literally the dumbest thing in the world

tonydisera [2:53 PM]
But what is weird is this clinvar del seems like an outlier.  The others are showing as left aligned.

Al [2:53 PM]
Do you have other examples?

tonydisera [2:54 PM]
I will try to look at some more.
Thank you for your explanation.  This is very confusing.

Al [2:54 PM]
Yeah, but I'm glad you uncovered this
http://varnomen.hgvs.org/recommendations/DNA/variant/deletion/
The several nucleotides example states you take the most 3' representation
This is only important with repeats, e.g. TTTTTTTTCAGCAGCAGTTTTTTTT
HGVS includes the coordinates of the deleted bases. VCF gives the position of the base to the left of the deleted bases

tonydisera [3:01 PM]
Would you mind a zoom call at some point to talk about this?

**Comment by tonydisera** [comment]
Added #274 to address issue with RAI deletion showing a ClinVar entry when pointed to ClinVar vcf that doesn't show when using ClinVar eutils.

**Comment by mvelinder** [comment]
I think this is fixed
