### ISSUE TITLE
Get rid of detailed clinvar in hover tooltip

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio.vue#257]
<img width="437" alt="screen shot 2018-10-13 at 6 16 25 pm" src="https://user-images.githubusercontent.com/8420103/46911274-480e6a80-cf14-11e8-8241-48569cf60382.png">
<img width="297" alt="screen shot 2018-10-13 at 6 16 33 pm" src="https://user-images.githubusercontent.com/8420103/46911277-4c3a8800-cf14-11e8-9e59-88aa2c11c4cd.png">

**Comment by mvelinder** [comment]
Not relevant anymore
