### ISSUE TITLE
Upgrade vue.js and vuetify to match genepanel.iobio

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio.vue#261]

**Comment by tonydisera** [comment]
Following are the vuetify versions of our apps:
Panel- ^1.1.0
Gene and Clin- ^1.0.4

Vue versions:
Panel- ^2.5.10
Gene and clin- ^2.3.4

Vuetify 1.1 + requires vue version of 2.5+
So when I had updated vuetify, I had to update the vue version as well. Also CSS classes have been renamed in vuetify 1.1 +. For example, .tooltip is now .v-tooltip

**Comment by AlistairNWard** [comment]
@tonydisera @WilliamRichards2017 How much effort is this, and what is the payoff? Trying to decide if this is a quick fix, high, or low priority

**Comment by WilliamRichards2017** [comment]
@AlistairNWard It's hard to tell exactly how much work it is, but I'd say it would be a fairly large effort to upgrade these.  I think the payoffs would be consistency across iobio apps, and long term maintainability.  My vote would be to put this in low priority.

**Comment by mvelinder** [comment]
Could be a release in itself and then we try to keep consistent across apps going forward?

**Comment by mvelinder** [comment]
I believe this is done
