### ISSUE TITLE
Add external links to MARRVEL, DECHIPER, and VarSome

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio.vue#262]

**Comment by tonydisera** [comment]
And gnomAD

**Comment by tonydisera** [comment]
https://varsome.com/position/hg19/chr19-1223121

**Comment by tonydisera** [comment]
Matt - I'd say in order of most important to least, DECIPHER, MARRVEL, VarSome

**Comment by tonydisera** [comment]
Matt: I'd say in terms of the order of the links: OMIM, HumanMine, GeneCards, NCBI, DECIPHER, MARRVEL, UniProt, GTex, ProteinAtlas (maybe change the wording here too?)

**Comment by tonydisera** [comment]
VarSome:  https://varsome.com/variant/hg19/17-17698535-G>A

**Comment by mvelinder** [comment]
Done
