### ISSUE TITLE
Add DANN score from VarSome API on Variant Detail

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio.vue#266]

**Comment by tonydisera** [comment]
![image (2).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5759f0b40b37b00e00e7d3d4/125516c66e82c728ace21e0d46e1999b2487c3e1dda0fd0fe64de29b234324676b5ee17e7187b02cbd467a075d5b4ead17585f46f9fadb7fa3e26a62964e49bc8f3900299f7744eeaa880dbe06b0218e4b85b3be894bc9eb392def99c2.png)

**Comment by tonydisera** [comment]
DANN is a pathogenicity scoring methodology developed by Daniel Quang, Yifei Chen and Xiaohui Xie at the University of California, Irvine. It is based on deep neural networks.

The value range is 0 to 1, with 1 given to the variants predicted to be the most damaging.

The authors request that you cite their publication.

**Comment by mvelinder** [comment]
DANN could be useful. In my anecdotal experience it tends to be very inflated and likely false positive in scores. The vast majority of variants I end up looking at have super high (> 0.9) DANN scores, while other prediction tools are more modest.
