### ISSUE TITLE
GNomAD link doesn't work for multi-allelics with extra anchor base

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio.vue#269]

**Comment by tonydisera** [comment]
![Screen Shot 2018-10-26 at 8.47.28 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5759f0b40b37b00e00e7d3d4/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236456f56b7191a370f1162c4f5d575ecc3c4a4356bcbbd671f3e57862804e0ebc836e0b26926c47aebc821ee901ba228e4cd7e2b9de1ad2f42f67b6d5db1063474f4dcbed5727a19141c95df24be74d5da11b3262e3742431.png)
![Screen Shot 2018-10-26 at 8.48.13 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5759f0b40b37b00e00e7d3d4/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236456f56b7191a370f116234f5e5c5ecc3c4a4356bcbbd671f3e57862804e0ebc836e0b26926c47aebc821ee901ba228e4cd7e2b9de1ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df24be74d5da11a3565e2702431.png)

**Comment by tonydisera** [comment]
![Screen Shot 2018-10-26 at 8.41.20 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5759f0b40b37b00e00e7d3d4/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236456f56b7191a370f1162a4f5d5f5ecc3c4a4356bcbbd671f3e57862804e0ebc836e0b26926c47aebc821ee901ba228e4cd7e2b9de1ad2f42f67b6d5db1063474f4dcbed5727a19141c95df24be74d5da3173361e0712431.png)
[Uploading Screen Shot 2018-10-26 at 8.41.27 PM.png...]

**Comment by AlistairNWard** [comment]
Are there examples of this? The screenshots appear to be dead.
