### ISSUE TITLE
Sidebar flipping

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio.vue#273]
If I select a gene in the side panel, it loads the info for the gene, then changes the view to the variants. If I just want to step through a few genes, it's annoying to have to keep switching the side panel back to genes, pick a gene, then have to change the view back to the genes as it gets flipped again.

**Comment by tonydisera** [comment]
Yes, I have seen this behavior too.  I agree.  It is very annoying!  I'll work on this.

**Comment by mvelinder** [comment]
Fixed
