### ISSUE TITLE
Called variant showing up in demo data set for AIRE in exon with NO coverage.

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio.vue#277]
This is a bug on production.  Notice that there is a called variant for AIRE even though there are no reads in this exon.  Also, notice that the zygosity is gt_unknown.

<img width="1089" alt="screen shot 2018-11-05 at 1 25 47 pm" src="https://user-images.githubusercontent.com/8420103/48024720-9c190300-e0fe-11e8-9f22-319eabf83d69.png">

<img width="645" alt="screen shot 2018-11-05 at 1 26 01 pm" src="https://user-images.githubusercontent.com/8420103/48024734-a2a77a80-e0fe-11e8-90b6-dbc854929d06.png">

**Comment by tonydisera** [comment]
It turns out that the bug was in vcf.iobio.js _parseGenotypes.  The proband had gt of ".", so it should have been treated as HOMREF.

**Comment by tonydisera** [comment]
I also found an edge case with multi-allelics with called variants.  In this case, the father is multi-allelic. The genotype for father is 1/2.  The genotype for proband and mother is 0/1.  
![Screen Shot 2018-11-05 at 2.29.22 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5759f0b40b37b00e00e7d3d4/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226454f66b7191a37af110224f5d5d5ecc3c4a4356bcbbd671f3e57862804e0ebc836e0b26926c47aebc821ee901ba228e4cd7e2b9de1ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df24ae54856a0103261e4742431.png)
![Screen Shot 2018-11-05 at 2.29.32 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5759f0b40b37b00e00e7d3d4/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226454f66b7191a37af110224f5c5d5ecc3c4a4356bcbbd671f3e57862804e0ebc836e0b26926c47aebc821ee901ba228e4cd7e2b9de1ad2f42f67b6d5db1063474f4dcbed5727a19041c95df24ae54856a0163665e7732431.png)


So the called variant for proband should not be displayed since this is really a "null" genotype in relationship to the second alt (of the multi-allelic).
![Screen Shot 2018-11-05 at 2.29.01 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5759f0b40b37b00e00e7d3d4/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226454f66b7191a37af110224f5f5e5ecc3c4a4356bcbbd671f3e57862804e0ebc836e0b26926c47aebc821ee901ba228e4cd7e2b9de1ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df24ae54856a2133164e4702431.png)

**Comment by tonydisera** [comment]
This can be fixed by excluding gt_unknown in SampleModel.setLoadedVariants inner function filterAndPileupVariants().  No we exclude gt_unknown zygosity as well.

`
 var isHomRef = feature.zygosity == null
           || feature.zygosity.toUpperCase() == "HOMREF"
           || feature.zygosity.toUpperCase() == "NONE"
           || feature.zygosity.toUpperCase() == "GT_UNKNOWN"
           || feature.zygosity == "";

        var inRegion = true;
        if (self.filterModel.regionStart && self.filterModel.regionEnd) {
          inRegion = feature.start >= self.filterModel.regionStart && feature.start <= self.filterModel.regionEnd;
        }

        var passesModelFilter = self.filterModel.passesModelFilter(model.relationship, feature);

        return isTarget && !isHomRef && inRegion && passesModelFilter;
`

**Comment by mvelinder** [comment]
No longer relevant
