### ISSUE TITLE
Proxy local file support in Gene.iobio

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio.vue#280]

**Comment by anderspitman** [comment]
@tonydisera just wanted to give you an update. I'm currently working on a bug with the proxy. I'm optimistic it will be done today then I can start working with you and adding support.

**Comment by tonydisera** [comment]
Cool.  Thanks for the update.

**Comment by anderspitman** [comment]
Hey @tonydisera, I believe the local file bug is fixed, and we're ready to start trying it out for gene. Basically you just need to `npm install --save fibridge-host` and use it as shown [here](https://github.com/anderspitman/fibridge-host). We have a publicly hosted `fibridge-proxy` instance running at `lf-proxy.iobio.io` (that's a capital i, sorry!). So you'll set that as the `proxyAddress` when creating the hoster. For a more complete example, you can see how I integrated it into bam [here](https://github.com/anderspitman/bam.iobio.io/blob/read-depth-optimization/client/app/components/partials/FileSelectButtonBar.vue#L169). 

If you're too busy with other things I can help but I'll need to split my time between this and removing binaryjs from minion.

**Comment by mvelinder** [comment]
Seems fixed
