### ISSUE TITLE
ClinVar histogram has wrong color for pathogenic variants.

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio.vue#281]

**Comment by tonydisera** [comment]
![Screen Shot 2018-11-06 at 3.35.28 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5759f0b40b37b00e00e7d3d4/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226454f56b7191a37bf1112e4f5d575ecc3c4a4356bcbbd671f3e57862804e0ebc836e0b26926c47aebc821ee901ba228e4cd7e2b9de1ad2f42f67b6d5db1063474f4dcbed5727a19041c95df24ae4495ca0143e63e2742431.png)

**Comment by tonydisera** [comment]
This is caused because the INFO fields have changed in VCF.  See #234

This will take a fix to the backend 'knownvariants' python script and redeploy of IOBIO backend service.  

Temporarily working around this issue by using older vcf format (summer 2017) for histogram counts only.

**Comment by mvelinder** [comment]
Seems fixed
