### ISSUE TITLE
Allele counts for homref not showing up in Variant Detail

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio.vue#288]

**Comment by tonydisera** [comment]
![Screen Shot 2018-12-05 at 5.55.56 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5759f0b40b37b00e00e7d3d4/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76216454f66b7191a37df1172e4f5a595ecc3c4a4356bcbbd671f3e57862804e0ebc836e0b26926c47aebc821ee901ba228e4cd7e2b9de1ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df24fe14852ac113e6ae1752431.png)

**Comment by tonydisera** [comment]
This is probably an unintentional side effect caused by filtering based on 'gt_unknown'

**Comment by tonydisera** [comment]
1.	 Gene.iobio should be able to show homrefs if the trio samples are in separate files.  (In fact, I thought I fixed gene.iobio to do this a while ago!)
2.	We won’t always have multi-sample vcfs, so we need to account for this in gene.iobio anyways.
3.	Gene.iobio requires multi-sample vcfs for affected/unaffected sibs, so long-term, we need to figure out a way to distinguish between one multi-sample vcf and multiple single-sample vcfs.

**Comment by mvelinder** [comment]
Seems fixed
