### ISSUE TITLE
Can't load local file .cram/.crai, need to change to Ander's local file proxy code

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio.vue#341]
See #142 comments from

**Comment by AlistairNWard** [comment]
How do you anticipate me contributing?!

**Comment by anderspitman** [comment]
This is something we need to do anyway as we transition to the new backend. @fgvieira I think we should have this working relatively soon.

**Comment by anderspitman** [comment]
@tonydisera this is working right? Obviously cram is working on gru, but are there any other subtle items attached to this that you remember?

**Comment by mvelinder** [comment]
Need to clarify this is working for the paper release

**Comment by AlistairNWard** [comment]
Duplicate of #597
