### ISSUE TITLE
Should counts on filter badges by variant or gene count?

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio.vue#35]
![Screen Shot 2018-04-03 at 9.45.52 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5759f0b40b37b00e00e7d3d4/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276454f06b7191a371f1162e4f5a5d5ecc3c4a4356bcbbd671f3e57862804e0ebc836e0b26926c47aebc821ee901ba228e4cd7e2b9de1ad2f42f67b6d5db1063474f4dcbed5727a19141c95df449e94c56a2173766ef7f2431.png)

**Comment by AlistairNWard** [comment]
I would vote for variant.
