### ISSUE TITLE
Disclaimer

### ISSUE THREAD

**Issue by mvelinder** [iobio/gene.iobio.vue#361]
Yeah, I don't think it needs to be in people's faces. Most other tools have an about that you have to navigate to to see the disclaimer. We could also add a link to the disclaimer in the footer

**Comment by mvelinder** [comment]
Maybe show a disclaimer on the Files page when people are putting their VCF and BAM links. Otherwise I think it's ok to be in the menu bar

**Comment by mvelinder** [comment]
![image](https://user-images.githubusercontent.com/22081541/76790497-8ef53500-6784-11ea-9eb0-3aaf080c6dab.png)
Let's put it under here as it's own button. Transparent background, relatively small

**Comment by tonydisera** [comment]
Can we make the disclaimer icon smaller?  It really stands out in the nav bar.  But maybe that is a good thing @AlistairNWard @mvelinder @WilliamRichards2017 ?

<img width="151" alt="Screen Shot 2020-03-24 at 11 56 12 AM" src="https://user-images.githubusercontent.com/8420103/77461793-bbcecb00-6dc8-11ea-9b06-5728a04b0d44.png">

**Comment by AlistairNWard** [comment]
Where can I see it?

**Comment by tonydisera** [comment]
Al, Will is reworking some code and will submit a new pull request.  So you can't see it on stage.gene.iobio.io until I merge the pull request.  Here is a screenshot.
<img width="1314" alt="Screen Shot 2020-03-24 at 2 42 42 PM" src="https://user-images.githubusercontent.com/8420103/77475036-c9db1680-6ddd-11ea-96e0-0c103da00389.png">

**Comment by AlistairNWard** [comment]
Ok, I see. It sort of seems like it's floating in no mans land.

Also, is the text changed? We need to make sure there is mention of commercial use having to go through Frameshift.

**Comment by mvelinder** [comment]
We still need to remove the mention of Frameshift. Like @AlistairNWard mentioned in the previous comment, 20 days ago. I also agree with @AlistairNWard 's previous comment that it shouldn't just be floating in the middle, push it to the right to be next to the three dots icon.

**Comment by mvelinder** [comment]
Let's move the button to the right, just to the left of the three vertical dots menu

**Comment by AlistairNWard** [comment]
Change the text in the disclaimer to:

**Terms of service**
**Academic Use**
Gene.iobio is free for all Academic use.

**Commercial Use**
Commercial use of gene.iobio is licensed through Frameshift Genomics. Please contact Frameshift at admin@frameshift.io to discuss any commercial use of this tool.

**Comment by WilliamRichards2017** [comment]
I'll do that now!
