### ISSUE TITLE
New static endpoints (geneinfo, etc)

### ISSUE THREAD

**Issue by mvelinder** [iobio/gene.iobio.vue#363]
the static clinvar files, genomebuild, geneinfo, and gene2pheno should all be running on gru now, both in the PE and on AWS. They’re running alongside the old ones, so you can move them over at your leisure https://backend.iobio.io/genomebuild
![image](https://user-images.githubusercontent.com/22081541/76558518-0e23f980-6463-11ea-9f8a-3871682b25c0.png)
![image](https://user-images.githubusercontent.com/22081541/76558531-12501700-6463-11ea-9908-66296a2bad4a.png)
Yeah definitely! Sorry for missing this

**Comment by anderspitman** [comment]
Assigning myself until we get #418 resolved.

**Comment by AlistairNWard** [comment]
@anderspitman I can't really test this.

**Comment by anderspitman** [comment]
I think we can close this, assuming @tonydisera signs off on it. #418 will likely be an ongoing situation. I'm still trying to collect clues as to what the issue is there. But I think this one is complete.
