### ISSUE TITLE
If the dbSnp id is shown, should it be clickable? (Al)

### ISSUE THREAD

**Issue by mvelinder** [iobio/gene.iobio.vue#364]
![image](https://user-images.githubusercontent.com/22081541/76558758-7ecb1600-6463-11ea-9036-559c1df3c968.png)
![image](https://user-images.githubusercontent.com/22081541/76558766-825e9d00-6463-11ea-8531-54c1ccc1fd4e.png)
![image](https://user-images.githubusercontent.com/22081541/76558779-87235100-6463-11ea-9cdd-68af35de5446.png)

richardsw2017 5 minutes ago
@tonyads Thank you! That makes me feel a lot better! I'll get this taken care of today and make sure that this will be the last time you have to look at this card.

Reply
Tony Di Sera an hour ago
@richardsw20171 Thanks for your help and getting this dev/testing loop back on track. It takes practice!

Reply
richardsw2017 2 hours ago
@tonyads Will do, I'm really sorry this fix has taken so many trials. I matched the font size to the Clin-var link but should have made it match the other row labels. The null error and showing the icon when there's no dbSNPId is 100% my bad. I will spend more time testing and paying attention to details to make sure you don't have to waste time finding my bugs/errors. Sorry again, I will work to be more careful and thorough

Reply
Tony Di Sera 3 hours ago
@richardsw20171 , looks like there is a null ref error with the rsid.
Screen Shot 2020-03-12 at 10.16.06 AM.png

Reply
Tony Di Sera 3 hours ago
This isn't working. When a variant doesn't have a dbSNPId, the icon is still showing up. Also, please make the font size 14 px (to match with other labels in this row). Screen Shot 2020-03-12 at 9.47.33 AM.png

@richardsw20171 , please spend more time testing and paying attention to the details. Click on multiple variants when testing any changes to the Variant card.

Reply
richardsw2017 Mar 5 at 1:37 PM
@mattvelinder @tonyads Sorry, I'll be more careful with this in the future!

Reply
Matt Velinder Mar 5 at 1:03 PM
@richardsw20171 to I think @tonyads 's larger point... we need to keep up on styling and consistency. Implementing is great, but the person implementing needs to test and make sure it's consistent with the wider app. Not trying to be harsh and I know it's just the dev version, but these are things Tony and I shouldn't really have to point out.

Edit - Delete
Tony Di Sera Mar 5 at 12:41 PM
This needs one more round of styling. Please use the same font weight and size as the ClinVar link. Also, the font size of the icon needs to be the same size as the ClinVar link. Screen Shot 2020-03-05 at 12.38.56 PM.png

Reply
richardsw2017 Feb 27 at 4:17 PM
@tonyads Will Do!

Reply
Tony Di Sera Feb 27 at 4:02 PM
Please add some padding to the right. And it looks like it might not be vertically aligned. Also, please make it the same style as 'Pathogenic ClinVar' where the text is gray and the icon is after the label.

Reply
Tony Di Sera Feb 18 at 1:50 PM (edited)
Thanks Will! Would you mind changing the link to this style? Screen Shot 2020-02-18 at 1.48.58 PM.png

**Comment by tonydisera** [comment]
@WilliamRichards2017, vertical alignment is something you have to pay attention to.  Notice how the dbSNP Id icon is sitting to low.  The user interface work requires paying attention to all of the tiny details.  That is what makes the IOBIO apps look professional.  I know this difference in alignment if very subtle, but all of these little oddities can pile up to make our apps look less than polished.

<img width="135" alt="Screen Shot 2020-03-12 at 7 15 09 PM" src="https://user-images.githubusercontent.com/8420103/76580707-7d671100-6496-11ea-9222-08f8fe22c6eb.png">


As compared to this.

<img width="184" alt="Screen Shot 2020-03-12 at 7 15 14 PM" src="https://user-images.githubusercontent.com/8420103/76580712-822bc500-6496-11ea-8cd0-aadb20863dbf.png">

**Comment by AlistairNWard** [comment]
Works for me.
