### ISSUE TITLE
Variant Inspect Card - Pedigree 'alt' bar needs better labels.

### ISSUE THREAD

**Issue by mvelinder** [iobio/gene.iobio.vue#365]
need labels 9 alt, 10 ref instead of 9 of 19

![image](https://user-images.githubusercontent.com/22081541/76558889-bc2fa380-6463-11ea-8a27-dfbb8ce02c7f.png)

Tony Di Sera Mar 5 at 1:06 PM
Let's get rid of the commas. Also, can we fix a related bug? It looks like when the sex is unknown (diamond symbol), the allele count bar overlaps with the symbol. Screen Shot 2020-03-05 at 1.04.34 PM.png

Reply
Tony Di Sera Mar 5 at 1:02 PM (edited)
Oops. I just realized that the allele counts don't show when we load a single proband, because the pedigree/genotype viz doesn't show. So we either need to change the logic to show the pedigree with the one node or add back the 'allele counts' popup when only a proband is provided.
Screen Shot 2020-03-05 at 1.01.01 PM.png

Reply
Matt Velinder Mar 3 at 1:15 PM
With newest push it looks fixed

Edit - Delete
Matt Velinder Mar 3 at 7:26 AM
Not fixed on stage.gene as launched from Mosaic (see image.png above)

**Comment by AlistairNWard** [comment]
@mvelinder @tonydisera @WilliamRichards2017 When there are specific examples in the description, can we include sample, gene, variant info so it can be recreated in testing?

**Comment by tonydisera** [comment]
Sure thing.  To show the proband as a diamond, try this.  Go to files and rather than clicking on 'Demo data', just enter the platinum demo for proband, mom, dad.

**Comment by AlistairNWard** [comment]
And go to what gene?
