### ISSUE TITLE
Can't show gene card alone unless files are loaded

### ISSUE THREAD

**Issue by mvelinder** [iobio/gene.iobio.vue#366]
![image](https://user-images.githubusercontent.com/22081541/76558985-eaad7e80-6463-11ea-8d92-3db3bad78e77.png)

Tony Di Sera Mar 5 at 12:56 PM
We need to show the gene viz here in the GeneVariants card (when no files are loaded). Screen Shot 2020-03-05 at 12.54.35 PM.png

Reply
richardsw2017 Feb 27 at 4:18 PM
@tonyads Shoot, sorry. It appears to be working for me so I'll make sure that this is taken care of in my next pull request.

Reply
Tony Di Sera Feb 27 at 4:05 PM
I tried this, but it doesn't seem to be working. I launch gene.iobio and type in a gene, but the screen is blank.

Reply
Tony Di Sera Feb 19 at 8:59 AM
Hi Will. I noticed that my change that I made yesterday to show gene variants card causes the card to show before others when files are loaded. Would you please address this with your fix?

**Comment by tonydisera** [comment]
I see the gene viz now, which is great.  But I'm wondering if we can put it in the same card (when gene is entered but no data loaded.)

<img width="1439" alt="Screen Shot 2020-03-24 at 12 11 42 PM" src="https://user-images.githubusercontent.com/8420103/77461951-fd5f7600-6dc8-11ea-8aac-7292249c8959.png">
