### ISSUE TITLE
Is IGV working properly?

### ISSUE THREAD

**Issue by mvelinder** [iobio/gene.iobio.vue#367]
I just looked at the demo data and clicked on the ClinVar pathogenic in RAI1. According to the allele counts, proband is hom, everyone else is het.   The IGV screenshot doesn't confirm that. The reads should basically be all green in the proband. Also, should we be including the sib in IGV?

The IGV screenshot doesn't confirm that. The reads should basically be all green in the proband. Also, should we be including the sib in IGV?

![image](https://user-images.githubusercontent.com/22081541/76559092-192b5980-6464-11ea-8aae-d7873a6af7c7.png)

richardsw2017 Mar 5 at 1:35 PM
@mattvelinder I spoke with Anders and we tested the newest version of IGV.js on crams in a static html page, and it seemed to work. Anders is refactoring his igv component to include the newest version of igv.js

Reply
Matt Velinder Mar 5 at 1:22 PM
@richardsw20171 This sounds right. Thanks!

Edit - Delete
richardsw2017 Mar 4 at 12:22 PM
@mattvelinder It looks like the problem for this project is that our version of igv.js does not support cram files. I think they may have added support for this in some version of it, but I can coordinate with Anders on this!

Reply
Matt Velinder Mar 3 at 1:17 PM
Seems to work on some projects but not all

Edit - Delete
Matt Velinder Mar 3 at 7:23 AM
When the track hangs there is also no way (that I see) to close the window, you're just stuck

Edit - Delete
Matt Velinder Mar 3 at 7:22 AM
We need to make sure we're testing multiple datasets for this... the one I just tried, https://mosaic.chpc.utah.edu/#/projects/39/samples (image.png above) did not work

Edit - Add Link as Attachment - Delete
richardsw2017 Feb 28 at 4:21 PM
Screen Shot 2020-02-28 at 4.19.54 PM.png Igv pileup appears to show the proband as Hom and everyone else as het in both the popout view and in the new tab view.

**Comment by anderspitman** [comment]
@mvelinder can you confirm the current broken behavior of IGV before I start changing things? When launching stage.gene I'm not seeing what you describe above with the demo data.

**Comment by mvelinder** [comment]
@anderspitman I've tested quite a few projects launched from Mosaic and am not having problems.

Project 39 on Mosaic is still broken however
![image](https://user-images.githubusercontent.com/22081541/77946397-73f3ec00-727f-11ea-8ab6-eda49e037a20.png)

So this might be a project by project troubleshooting. Could you check if the cram data is accessible for project 39? https://mosaic.chpc.utah.edu/#/projects/39/samples Or if there is anything different for project 39 than project 4 https://mosaic.chpc.utah.edu/#/projects/4/ or project 113 https://mosaic.chpc.utah.edu/#/projects/113/ ?

**Comment by anderspitman** [comment]
@mvelinder pileup view is working for me for the proband of project 39, gene NPR1. What steps did you follow to get it to fail?

**Comment by anderspitman** [comment]
GFI1 SNP 1:92946625 (which you have in your screenshot above) is also working for me.

**Comment by mvelinder** [comment]
From our Slack discussion: we will get an updated igv.js (@anderspitman responsibility) and implement launching in a new tab (@WilliamRichards2017 responsibility).

After we implement these changes we can test again and see if it resolves this (admittedly intermittent and sporadic) issue.

**Comment by anderspitman** [comment]
Ok I've released the new version of vue-pileup (0.11.0). @WilliamRichards2017 can you integrate it and test it out? There is one API change. variantIndexURL is now required in addition to variantURL. You should be able to follow the same logic as alignmentIndexURL. Let me know if you have any questions.
