### ISSUE TITLE
Insufficient coverage for Mother/Father doesn't show in VariantCardAll

### ISSUE THREAD

**Issue by mvelinder** [iobio/gene.iobio.vue#368]
With the current version of gene, the insufficient coverage glyphs and marked exons would show.  Now, this functionality has disappeared in VariantCardAll.

![image](https://user-images.githubusercontent.com/22081541/76559477-e2097800-6464-11ea-9b1b-1c5b48ab73ca.png)
![image](https://user-images.githubusercontent.com/22081541/76559552-ffd6dd00-6464-11ea-9c03-d8ae2fac0b59.png)
![image](https://user-images.githubusercontent.com/22081541/76559563-0402fa80-6465-11ea-8a2f-0972f083ac79.png)

Tony Di Sera Mar 5 at 12:53 PM
I didn't think of it at the time, but I think we should show the gene viz so that the user can hover over the exons to see the coverage stats, regardless if the coverage is flagged as insufficient.

Reply
Tony Di Sera Mar 5 at 12:51 PM (edited)
It looks like the tooltip for father might be showing the proband's gene coverage as the stats look identical. Screen Shot 2020-03-05 at 12.48.24 PM.png Screen Shot 2020-03-05 at 12.48.12 PM.png

To reproduce this, use the demo dataset and select MYLK2 and then bump up the min and mean coverage. Screen Shot 2020-03-05 at 12.48.32 PM.png

I also noticed that father showed insufficient coverage, but the tooltip doesn't show the "< [threshold]" in highlighted text to the right. Screen Shot 2020-03-05 at 12.48.02 PM.png

**Comment by tonydisera** [comment]
Looks like this is fixed.  On minor issue...  Can you show the cutoffs (in pink) for mother and father coverage tooltips like we do for proband?
<img width="282" alt="Screen Shot 2020-03-24 at 12 08 49 PM" src="https://user-images.githubusercontent.com/8420103/77461594-6c889a80-6dc8-11ea-8b6f-8366da06913a.png">

**Comment by WilliamRichards2017** [comment]
Yeah for sure!
