### ISSUE TITLE
Create a 'simplified' gene.iobio to be used by Nebula genomics

### ISSUE THREAD

**Issue by mvelinder** [iobio/gene.iobio.vue#369]

**Comment by tonydisera** [comment]
See https://docs.google.com/document/d/1tm1e3TFNTC5HNv0k2BtQoamtE9jeLnPsfkv6jUQFFuo/edit

**Comment by mvelinder** [comment]
@tonydisera can we close this out?

**Comment by tonydisera** [comment]
I need to deploy it to stage first.  Let's keep it in 'In progress' until I merge.

**Comment by mvelinder** [comment]
Sorry, I thought it was done. I'll let you handle it

**Comment by tonydisera** [comment]
This can be reviewed/tested on https://dev.gene.iobio.io

**Comment by mvelinder** [comment]
I'm not sure what specifically needs testing, but I played around with it and it looks good to me.

**Comment by mvelinder** [comment]
Assuming @tonydisera 's testing is sufficient
