### ISSUE TITLE
Ask MyGene2 to test new version of gene.iobio

### ISSUE THREAD

**Issue by mvelinder** [iobio/gene.iobio.vue#370]

**Comment by tonydisera** [comment]
This can be tested here:
https://stage.mygene2.iobio.io/?mygene2=true&mode=basic

**Comment by mvelinder** [comment]
I get this error on launching, but the demo data looks to be working ![image](https://user-images.githubusercontent.com/22081541/78083569-19d45300-7373-11ea-939b-7c9f0c7fd76c.png)
