### ISSUE TITLE
Fix gene.model.db for RefSeq, swapping X and Y chromosomes.

### ISSUE THREAD

**Issue by mvelinder** [iobio/gene.iobio.vue#371]
select distinct build, seqid, chr from genes where source = 'refseq' and chr in ('chrX', 'chrY') order by chr, seqid, build

update genes set chr = 'chrY' where seqid in ('NC_000024.9', 'NC_000024.10') and source='refseq'
update genes set chr = 'chrX' where seqid in ('NC_000023.10', 'NC_000023.11') and source='refseq'

update transcripts set chr = 'chrY' where seqid in ('NC_000024.9', 'NC_000024.10') and source='refseq'
update transcripts set chr = 'chrX' where seqid in ('NC_000023.10', 'NC_000023.11') and source='refseq'

**Comment by mvelinder** [comment]
I'm not equipped to test this, but will consider it fixed based on @tonydisera 's review

**Comment by anderspitman** [comment]
@tonydisera this is related to the updated gene.iobio.db, right? So that's working correctly?
