### ISSUE TITLE
Variants side panel - When variant has note but is not sig or unknown-sig add to separate filter category titled 'Notes added'

### ISSUE THREAD

**Issue by mvelinder** [iobio/gene.iobio.vue#376]

**Comment by AlistairNWard** [comment]
@tonydisera @WilliamRichards2017 @mvelinder 

See #374 for updating comment.

This should be a separate 'Notes Added' category, but is being added to 'Reviewed'. All other variants in reviewed have a badge that shows the attached significance, but the one that only has a note has no badge. Does this seem ok for an average user? Or should we have a separate 'Notes Added' category, or add a badge 'Has notes' as well as a significance badge?

![Screen Shot 2020-04-13 at 1 30 10 PM](https://user-images.githubusercontent.com/523111/79143262-eb9b3e00-7d8a-11ea-9525-3917006d42bb.png)

**Comment by tonydisera** [comment]
Yeah, this is not clear.  And we do something kind of strange in clin.iobio, setting variants with notes (but no interpretation to 'Unknown Significance'.  So we need a consistent approach for how we deal with variants that don't have an interpretation but do have notes.  I'm not sure the best way to address this.

**Comment by AlistairNWard** [comment]
See #175 for clin. If a note is added, the variant is marked as Unknown Significance. So it's ok for the variant to go to the Reviewed section in the left menu because it does have a significance

**Comment by WilliamRichards2017** [comment]
Okay sounds good, I can implement that so it's consistent with clin!
