### ISSUE TITLE
REACH: Filter variant view

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio.vue#388]
It would be nice to limit the variants viewed in the filter card. For example, someone might have created a custom filter and there are multiple variants in a gene that pass the filter. If there was an icon attached to the filter (probably with the trashcan, edit symbol etc), that would allow the user to view only the variants passing this filter, that would make it quick and easy to identify the relevant variants.

THIS IS A REACH ISSUE!

**Comment by mvelinder** [comment]
Use labels, not text in the header you dingo!
