### ISSUE TITLE
Canceling a new filter creates a new filter anyway

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio.vue#389]
Click on New Filter, then click cancel. The new filter is created and added to the list anyway.

One caveat; if you do this when the genes are still being analysed, the new filter isn't added, but the name (custom-filter-id) is still incremented, so when you do create a filter after the genes are analysed, the first filter is called custom-filter-3 or whatever you got to!

**Comment by mvelinder** [comment]
Fixed
