### ISSUE TITLE
When services like geneinfo are not responding, we need to inform the user in gene.iobio with a user-friendly message

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio.vue#391]
Today, Al was running into problems when demoing gene.iobio because the geneinfo service wasn't responding.  

In Al's word (imagine the British accent): "I was demoing and in this instance, the screen is just blank, so I don't know whether it's just being slow and I should wait etc. If it said down for maintenance, it's way easier to explain away!"

In Tony's word (imagine an Eastern Colorado accent): "That is a fair point.  In this case, the services are timing out after many seconds, so we would need to 1) decrease the timeout 2) catch the error in gene.iobio and show a sensible message.  Yes, we should do this.  I’ll add an issue."

**Comment by tonydisera** [comment]
![Screen Shot 2020-03-19 at 12 07 38 PM](https://user-images.githubusercontent.com/8420103/77089913-11bc0100-69cc-11ea-8e19-8752999a8125.png)

**Comment by AlistairNWard** [comment]
The description really transported to the conversation!!

**Comment by mvelinder** [comment]
Seems fixed based on our current error reporting
