### ISSUE TITLE
Transcript menu is empty

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio.vue#392]
I noticed this week that the transcript menu is broken.  My best guess is this was broken when we introduced the ability to show the Gene card (GeneVariantsCard.vue) before the data is loaded.  I think this change probably cause an event to not fire when a gene is loaded.  

Also, the transcript ID doesn't change when I switch to a new gene.  It just stays on the transcript for the first gene that was loaded.

This will need to get fixed before we can release 4.0 of gene.

<img width="1535" alt="Screen Shot 2020-03-21 at 11 33 25 AM" src="https://user-images.githubusercontent.com/8420103/77232643-ea9a3680-6b67-11ea-9781-92e92c1b8470.png">

**Comment by WilliamRichards2017** [comment]
I'll make sure to include this fix in the pull request I submit at the end of the day

**Comment by tonydisera** [comment]
Thanks Will!
