### ISSUE TITLE
Switch clin.iobio to use gene sets instead of variant sets

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio.vue#401]

**Comment by mvelinder** [comment]
See clin repo issue too https://github.com/iobio/clin.iobio/issues/152

**Comment by tonydisera** [comment]
See clin repo issue https://github.com/iobio/clin.iobio/issues/161

**Comment by mvelinder** [comment]
@tonydisera that issue is deleted and the issue on clin https://github.com/iobio/clin.iobio/issues/152 has been closed. I'm going to close this one. Please reopen if this is incorrect.

**Comment by AlistairNWard** [comment]
Yes, this is a clin issue and it's resolved, so should be closed.
