### ISSUE TITLE
Launch from Mosaic with gene TRNAD11, the 'No transcripts popover' stays for a super long time

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio.vue#422]
<img width="393" alt="Screen Shot 2020-04-02 at 3 15 01 PM" src="https://user-images.githubusercontent.com/8420103/78300548-e91c2700-74f4-11ea-8ab0-6b1a2df0f57c.png">

@mvelinder , I took the liberty of adding this to the 4.0 milestone since it is a super annoying bug.

**Comment by WilliamRichards2017** [comment]
It looks like the transcript canonical fix changed the behavior of this issue.  Now, we never hit the catch statement that emits the unable to find transcript snackbar.  Instead, the transcript is populated as 'null', and we do not remove the gene from the gene model.  I'm currently looking into how to properly emit the snackbar and remove the gene from the gene-model when a transcript is null.  Should I submit the fix in this issue, or would you prefer I close this and make a new issue that describes the problem after my transcript changes were merged to dev?

**Comment by WilliamRichards2017** [comment]
<img width="465" alt="Screen Shot 2020-04-06 at 5 46 07 PM" src="https://user-images.githubusercontent.com/15776714/78615543-13d8e900-782f-11ea-88f3-9bdb66914d6a.png">
