### ISSUE TITLE
The label in the pedigree/genotype is showing n/a material and n/a paternal even though there are variants.

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio.vue#444]
This is from the MPPH project. You should see this problem on most (or all?) variants you click on.
<img width="186" alt="Screen Shot 2020-04-08 at 9 35 46 AM" src="https://user-images.githubusercontent.com/8420103/78804373-4abd1500-797d-11ea-839e-b57b2e822ccb.png">
<img width="74" alt="Screen Shot 2020-04-08 at 9 35 51 AM" src="https://user-images.githubusercontent.com/8420103/78804398-4ee93280-797d-11ea-9435-bccb7bf49342.png">

**Comment by mvelinder** [comment]
In my testing this doesn't seem to be an issue. I'll close it for now but let's keep an eye on it.
