### ISSUE TITLE
Copy updated geneinfo.db file to AWS gru backend deployment

### ISSUE THREAD

**Issue by anderspitman** [iobio/gene.iobio.vue#447]

**Comment by anderspitman** [comment]
This is dependent on https://github.com/iobio/iobio-gru-backend/issues/36.

**Comment by anderspitman** [comment]
Nevermind on being dependent on https://github.com/iobio/iobio-gru-backend/issues/36, I went ahead and deployed the new db.

**Comment by anderspitman** [comment]
@tonydisera can you review this? I guess in this case it basically means once you're confident it's working.

**Comment by tonydisera** [comment]
Yep.  It is working on both Utah Mosaic backend and AWS backend.  Thank you Anders!
Here's how it looks on production (SAM is supposed to be on chr X)
<img width="1045" alt="Screen Shot 2020-04-09 at 6 44 42 PM" src="https://user-images.githubusercontent.com/8420103/78952294-551d0300-7a92-11ea-973a-6519669a6e7d.png">

Here's how it looks on stage.gene.iobio:
<img width="978" alt="Screen Shot 2020-04-09 at 6 46 26 PM" src="https://user-images.githubusercontent.com/8420103/78952334-75e55880-7a92-11ea-97e6-889d1039ba45.png">

**Comment by mvelinder** [comment]
Assuming previous testing is sufficient

**Comment by tonydisera** [comment]
Yes.   I made sure that this is working on stage.gene.iobio.io
