### ISSUE TITLE
The 'analysis saved' snackbar used to be positioned to show next to the floating action button.  Now it appears in the center.

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio.vue#470]
Also, the first time an analysis is saved, it sticks around a super long time.
<img width="403" alt="Screen Shot 2020-04-16 at 6 00 44 PM" src="https://user-images.githubusercontent.com/8420103/79518146-8f941c00-800d-11ea-8747-07499e0180c4.png">

**Comment by mvelinder** [comment]
Center screen and fade?
