### ISSUE TITLE
After setting the variant interpretation,  I can't close the panel.

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio.vue#480]
<img width="591" alt="Screen Shot 2020-04-20 at 8 39 49 PM" src="https://user-images.githubusercontent.com/8420103/79819432-35fe5b00-8347-11ea-8d2a-2194fe581cb6.png">

**Comment by mvelinder** [comment]
Crazy, never noticed this! Nice catch @tonydisera !
