### ISSUE TITLE
Should look into caching for /geneinfo and /gene2pheno

### ISSUE THREAD

**Issue by anderspitman** [iobio/gene.iobio.vue#498]
Both of these services take ~200-400ms on my local machine (though strangely gene2pheno only takes ~60ms in production). This could be cut to almost nothing with some basic HTTP caching. We're only sending a few parameters, so I think this is doable.

The one caveat is if we expect the cache to grow huge. In practice I suspect a relatively small number of genes are going to be queried quite a bit, but others would know more about that than me. Also, it's likely that a given user will be interested in specific genes at any one time, which would mean their browser could cache gene data, which would completely avoid the request. Even if the server cache does get huge it might be worth it.

**Comment by anderspitman** [comment]
PS @tonydisera @stefinfection there's a good chance this would solve the failed request problem without having to add a new endpoint.

**Comment by AlistairNWard** [comment]
I'm closing this. We'll be designing a new caching / saving system

**Comment by anderspitman** [comment]
@AlistairNWard this issue is talking about backend caching. I'll open a new issue on the gru repo and to this one. You can leave it closed.
