### ISSUE TITLE
Selecting a clinvar significance in custom filters doesn't work

### ISSUE THREAD

**Issue by WilliamRichards2017** [iobio/gene.iobio.vue#519]

**Comment by WilliamRichards2017** [comment]
described issue from Al - "Ok. If I create a new filter and just set ClinVar significance to pathogenic then create the filter; the filter is created, but the clinvar significance requirement disappears, so basically all variants get dropped into the filter. If I edit the filter, I see that nothing is applied, so set pathogenic again, but it doesn't get applied"

**Comment by AlistairNWard** [comment]
Fixed
