### ISSUE TITLE
ACMG should probably show only ClinVar pathogenic/likely pathogenic variants as default filter.  Need to show variants for Proband, Mother and Father.

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio.vue#52]

**Comment by tonydisera** [comment]
Marti suggested into today's meeting that we break the ACMG filters into 'Pathogenic', 'LOF', and 'VUS'.

**Comment by AlistairNWard** [comment]
Our filters are based on the values in ClinVar and we should probably just stick to those, rather than trying to interpret them to other values.
