### ISSUE TITLE
Fix recessive and filtered variants issue

### ISSUE THREAD

**Issue by mvelinder** [iobio/gene.iobio.vue#540]
Project https://mosaic.chpc.utah.edu/#/projects/371/samples example that @AlistairNWard found

**Comment by tonydisera** [comment]
Project with id 371 is no longer there, but I think this was A677 project.

Here is the note:

<img width="1272" alt="Screen Shot 2020-06-26 at 5 19 36 PM" src="https://user-images.githubusercontent.com/8420103/85908180-4d3b4800-b7d1-11ea-90e5-e2bfabe4f7cd.png">

**Comment by tonydisera** [comment]
I'm going to improve the label on Edit Filter so this is more obvious.

**Comment by AlistairNWard** [comment]
Ok cool. I just added a comment in Mosaic. The label doesn't mention GnomAD, or popmax. Is the filter just on popmax AF, or the gnomAD AF?
