### ISSUE TITLE
Gene tracks don't load in clin

### ISSUE THREAD

**Issue by adityaekawade** [iobio/gene.iobio.vue#541]
Gene tracks are not loading or get stuck if variants are not found in genes when launched from clin.iobio. 

Eg: 
Launch clin.iobio with demo data > go to review variants > 
viz tracks don't load. 

To test with clin locally, you can either use the stable branch `dev` or the current branch `custom-saving-1`.

<img width="1105" alt="Screen Shot 2020-06-23 at 11 57 22 AM" src="https://user-images.githubusercontent.com/16284713/85446027-ddb32780-b548-11ea-826b-f79a6d96f0c7.png">

Error messages in console: 
<img width="871" alt="Screen Shot 2020-06-23 at 11 57 30 AM" src="https://user-images.githubusercontent.com/16284713/85446081-e86dbc80-b548-11ea-8b78-be2a580184ad.png">

**Comment by mvelinder** [comment]
Assumed complete based on Adit's testing and comments on the linked pull request
