### ISSUE TITLE
ClinVar track can make variants disappear

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio.vue#550]
I see variants for a proband, then select the clinVar track (variants), and all variants disappear. If I get rid of the clinVar track, the proband variants come back. Click on other tracks, click on ClinVar and all variants (proband and ClinVar) are visible, but click off the modal to close it, all variants disappear. I'll add a video on Slack to show

**Comment by tonydisera** [comment]
I'd like to assign this to Will as I think this was working in 4.1.

**Comment by tonydisera** [comment]
I suspect this is related to the new feature to show/hide variants.

**Comment by mvelinder** [comment]
Looks to be working in my testing
