### ISSUE TITLE
Variants count badge not corresponding

### ISSUE THREAD

**Issue by adityaekawade** [iobio/gene.iobio.vue#551]

**Comment by adityaekawade** [comment]
<img width="1092" alt="Screen Shot 2020-07-09 at 11 16 33 AM" src="https://user-images.githubusercontent.com/16284713/87075877-dbea9480-c1d5-11ea-85fa-ae11da07788e.png">

**Comment by mvelinder** [comment]
Looks good based on @WilliamRichards2017 's screenshot and testing
