### ISSUE TITLE
Saved analysis in  gene.iobio doesn't save gene (when launched from Mosaic with gene name)

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio.vue#553]
1. Launch gene from Mosaic, entering a gene name
2. After gene is loaded, save analysis
3. Go to 'Analyses' in Mosaic and launch
4. Gene that you launched with doesn't load in gene.

**Comment by mvelinder** [comment]
If I understand the issue correctly @tonydisera , this looks fixed. Do you agree?

**Comment by AlistairNWard** [comment]
Nope, not fixed

**Comment by mvelinder** [comment]
@AlistairNWard clarified, I guess it is NOT fixed on my testing on dev.

**Comment by mvelinder** [comment]
This will be addressed in the removal of auto-saving in the next release

**Comment by AlistairNWard** [comment]
This does seem to be fixed now. Can someone else confirm?

**Comment by mvelinder** [comment]
Think it got reopened when I moved it, seems fixed

**Comment by AlistairNWard** [comment]
I just tried again and it is fixed.
