### ISSUE TITLE
Three dots doesn't make sense for adding multiple genes

### ISSUE THREAD

**Issue by mvelinder** [iobio/gene.iobio.vue#556]
![image](https://user-images.githubusercontent.com/22081541/87427394-ee7e1880-c59d-11ea-87d3-a1dbdd91f265.png)

The three vertical dots is more of a menu button than a single action button in my mind. We should replace this with a + or a button that indicates this is how you add a list of genes

**Comment by AlistairNWard** [comment]
Superseded by #660
