### ISSUE TITLE
Keep selected/circled variant when using zoom and while selecting different variant while zoomed

### ISSUE THREAD

**Issue by mvelinder** [iobio/gene.iobio.vue#560]
Testing on the quarantest build above and the demo data...

It looks like the selected variant is not retained when using the zoom feature.

Select a variant in the track by clicking on it, variant is selected
![image](https://user-images.githubusercontent.com/22081541/87977670-5e077280-ca8c-11ea-8936-99b77b8e307d.png)

Toggle zoom to on, variant is still selected
![image](https://user-images.githubusercontent.com/22081541/87977750-79727d80-ca8c-11ea-9de9-8d85d58a003b.png)

Drag to zoom on the exon, variant selection is lost
![image](https://user-images.githubusercontent.com/22081541/87977772-81cab880-ca8c-11ea-834c-65b311e51b65.png)

I'm not sure if this was always how it worked or if it has since broken, but let's get it fixed regardless

**Comment by AlistairNWard** [comment]
Seems to be fixed
