### ISSUE TITLE
Affected symbol position

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio.vue#561]
The symbol showing a sample is affected can be behind the allele counts.

![Screen Shot 2020-07-20 at 3 28 25 PM](https://user-images.githubusercontent.com/523111/87978048-bf840d00-ca9d-11ea-828e-10ad27666757.png)

**Comment by AlistairNWard** [comment]
You can replicate this on the demo data by just going to the data selection and making everyone affected.

**Comment by tonydisera** [comment]
To test, run platinum demo trio and toggle on affected for Mother and Father in Files dialog.  Click on a variant.  Now there should be room for the allele bars and the affected glyph.
<img width="152" alt="Screen Shot 2020-11-20 at 7 09 34 PM" src="https://user-images.githubusercontent.com/8420103/99865001-f2313580-2b63-11eb-8496-c268199142ce.png">

**Comment by mvelinder** [comment]
@tonydisera are these changes on stage.gene?

I tested there and toggled mom and dad affected status as on 
![image](https://user-images.githubusercontent.com/22081541/100144200-ab895700-2e53-11eb-95f2-ac46d6538264.png)

But I don't see an affected status symbol for dad 
![image](https://user-images.githubusercontent.com/22081541/100144237-bb08a000-2e53-11eb-9ecf-947040a92850.png)

**Comment by AlistairNWard** [comment]
I see this as working
