### ISSUE TITLE
Multialign - why doesn't conservation info show in Variant Detail for PDGFB?  It appears to be available in UCSC browser.

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio.vue#565]
<img width="1108" alt="Screen Shot 2020-07-23 at 5 06 02 PM" src="https://user-images.githubusercontent.com/8420103/88346991-ef821900-cd06-11ea-8ffd-a17d71bf9974.png">
<img width="947" alt="Screen Shot 2020-07-23 at 5 06 45 PM" src="https://user-images.githubusercontent.com/8420103/88347001-f27d0980-cd06-11ea-993b-0458b80a627c.png">

**Comment by AlistairNWard** [comment]
@tonydisera Is this fixed? I see conservation there:

![Screen Shot 2020-09-22 at 4 21 49 PM](https://user-images.githubusercontent.com/523111/93933499-c3c3e500-fcef-11ea-93ce-c0e94cc4c70e.png)

Other comments:
1. The gray no entry symbol next to not conserved is confusing to me. I don't know what it is supposed to imply.
2. This variant is listed as not conserved followed by -1.723. Could we add a tooltip to explain what this number means?

**Comment by mvelinder** [comment]
Looks fixed to me, closing
