### ISSUE TITLE
Link to PubMed gene page

### ISSUE THREAD

**Issue by mvelinder** [iobio/gene.iobio.vue#581]
PubMed provides a list of publications based on the gene name(s) associated with that paper... we should add this to External Links in the gene card 

https://pubmed.ncbi.nlm.nih.gov/?from_uid=10159&linkname=gene_pubmed

![image](https://user-images.githubusercontent.com/22081541/90060390-e2bb6a00-dca1-11ea-885f-0634c4271eb2.png)

**Comment by mvelinder** [comment]
We can change default sorting too via the URL, this for instance is sorting on most recent. I'd actually vote for this most recent sorting as default

https://pubmed.ncbi.nlm.nih.gov/?sort=date&linkname=gene_pubmed&from_uid=10159

**Comment by AlistairNWard** [comment]
Seems to be fixed
