### ISSUE TITLE
Clicking ClinVar variant in zoomed track resets zoom level

### ISSUE THREAD

**Issue by mvelinder** [iobio/gene.iobio.vue#582]
Load clinvar track
Zoom in on a region that includes a clinvar variant
Click clinvar variant
Zoom level resets and everything is confusing

![image](https://user-images.githubusercontent.com/22081541/90063031-f668cf80-dca5-11ea-8db5-092a2becc2de.png)
![image](https://user-images.githubusercontent.com/22081541/90063046-fb2d8380-dca5-11ea-8941-27ed0c8913d2.png)

**Comment by AlistairNWard** [comment]
Yep, I see the same thing. The zooming should be tested thoroughly, e.g. select a variant, zoom and the variant is deselected, which I think already has an issue

**Comment by AlistairNWard** [comment]
Seems to be fixed
