### ISSUE TITLE
Launching gene multiple genes from Mosaic alters how variants are annotated

### ISSUE THREAD

**Issue by mvelinder** [iobio/gene.iobio.vue#589]
Using this project https://mosaic.chpc.utah.edu/#/projects/371/samples

Launch gene with these two genes **in this order**
![image](https://user-images.githubusercontent.com/22081541/90265555-f7b60b80-de0f-11ea-894b-394b93936338.png)

Get this:
![image](https://user-images.githubusercontent.com/22081541/90265691-2cc25e00-de10-11ea-8334-d4da2235ddc4.png)
Where BRWD3 is NOT annotated as X-linked recessive and does not show up on the variant list

Launch gene with these two genes **in this order**
![image](https://user-images.githubusercontent.com/22081541/90265656-203e0580-de10-11ea-9f53-fe701908e481.png)

Get this:
![image](https://user-images.githubusercontent.com/22081541/90265914-7f9c1580-de10-11ea-8993-e11c42cf1170.png)
Where ATP6AP2 is NOT annotated as X-linked recessive and does not show up on the variant list

Launching ATP6AP2 and BRWD3 as part of a gene list launched from Mosaic seems to work fine and as expected
![image](https://user-images.githubusercontent.com/22081541/90266133-cab62880-de10-11ea-92d1-1503acab5a79.png)

**Comment by AlistairNWard** [comment]
I launched in both orders, and both variants appeared in the left panel both ways. Fixed
