### ISSUE TITLE
Local cram files

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio.vue#597]
If you try and select local cram/crai, gene errors and asks for bam/bai.

**Comment by mvelinder** [comment]
Error today for local cram, even after selecting both a cram and crai

"You must select BOTH a compressed bam and an index (.bai) file"

1) it should support local crams
2) we should change the wording for "Enter bam URL" to "Enter bam/cram URL" and the error message about indexes to indicate bam or cram indexes .bai or .crai
