### ISSUE TITLE
~Gray out load button if Bam file isn't provided, handle vcf url vs local vcf differently~ add optional message in bam file text field

### ISSUE THREAD

**Issue by WilliamRichards2017** [iobio/gene.iobio.vue#616]

**Comment by AlistairNWard** [comment]
Fill in everything and delete the BAM and the Load isn't grayed out. Probably not important for paper release

**Comment by stefinfection** [comment]
I'm not sure this is the desired behavior - the application still works without the coverage track. Maybe we can just write '(optional)' in the text field placeholder to be more explicit? @AlistairNWard

**Comment by AlistairNWard** [comment]
You're right Steph. Let's just put optional in the text field to make it clear.
