### ISSUE TITLE
gene / variant sources for clin

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio.vue#625]
Clin will have genes and variants coming from different sources. At the simplest, genes containing the variants in the variant set and the top genes generated in the select phenotypes step. The user needs to be clear that there are different sources and be able to distinguish why each variant and gene is in the list.

**Distinguish source**
The left panel should distinguish have an icon (I'll throw up a mockup of an initial idea later today) that identifies the source. This will also need a legend. This can be shared by both panels.

**Variant detail**
In the variant detail, we should indicate the source of the variant, e.g. from the variant set, the gene list, ACMG genes etc.

**Comment by AlistairNWard** [comment]
Purely a first thought. Feel free to criticise and make suggestions. The variant tab could show the same basic change:

![Uploading Asset 1.png…]()

**Comment by mvelinder** [comment]
I'd vote glyphs/icons for source instead of numbers, more visual?

**Comment by AlistairNWard** [comment]
The problem is if you have e.g. four sources, we would need 4 glyphs. It would quickly get confusing as to what they all mean.

**Comment by adityaekawade** [comment]
What are the different sources that we expect? "Imported set", "list from phenotypes", "ACMG genes" and ...?

**Comment by AlistairNWard** [comment]
Initially we will have genes present because they contain variants in the selected variant set, and genes that were in the list of genes generated in the phenotype step. No need to worry about ACMG yet, I was just making the point that we could imagine there being more sources in the future, so our solution should be extensible. We could, for example, launch clin from Mosaic with a variant set and a gene set, so then we would additionally have a gene set as a source. I would say for now though, we just worry about the variant set and the phenotype generated list.

**Comment by adityaekawade** [comment]
Just wanted to give a quick update, I am able to pass the genes from both sources (imported sets and genes from phenotypes) and indicate their source in the "review-variant" step. I will work on the aesthetics, and test it on a few edge cases and push it to the dev version for you to test. 
 
<img width="1674" alt="Screen Shot 2020-09-24 at 2 06 13 PM" src="https://user-images.githubusercontent.com/16284713/94200427-41fac580-fe6f-11ea-92e7-13b3403a7a2a.png">

**Comment by AlistairNWard** [comment]
This is great @adityaekawade . I feel like this one might be a bit trickier to get the aesthetics right, so any comments by anyone else looking would be good. In particular, I made a mistake in the mockup, the source should be under "Variant in PRX" in the variant detail card, not the card above. I think this will be the hardest piece to get right. We might no want the text, rather something like "Sources:" and badges with "1", and "2", then rely on the legend to define 1 and 2. This might take a couple of iterations, so it would be better to have a few quick options for comment.

**Comment by adityaekawade** [comment]
Yeah, I will move the source information in the variant detail card. I feel showing text is a better option here instead of badges since we have some space.

**Comment by mvelinder** [comment]
Functionality is great. But I agree we should try to make this more intuitive about what the sources are. I'll think about it.

We could also think about adding things into the Gene Associations area. Seems there is overlap between the two areas.
