### ISSUE TITLE
Should focus return to top variant when data is loaded?

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio.vue#627]
Open the demo data and click on a gene before analysis is complete. As soon as analysis completes, focus returns to RAI1, which is annoying if you were wanting to look at the gene you selected.

**Comment by WilliamRichards2017** [comment]
I'm not sure about this.  If you select a variant in a different gene, the focus won't be returned to the first flagged variant.  I think the point of the focus returning to the first selected variant, is to take users directly to the variant card for the 'most important' variant.  I think the autoselecting a variant is good for new users, but might be bad for regular users.  I could also add in a dialog prompt asking users if they want to jump to the highest prioritized variant once the data has finished loading.  @AlistairNWard @mvelinder @tonydisera Anyone have any thoughts on this?

**Comment by AlistairNWard** [comment]
I don't think we should add a dialog. We want to avoid forcing users to have to click too many things.

My opinion is that a new user would probably wait till things are loaded and then they'd be taken to the top variant. Even if you've selected something else, the variant list order should be enough to make it clear what we think is important.

As a returning user, I might be opening up an analysis to quickly check on a variant, or a particular gene. So as soon as gene opens, I'll select the gene I want to look at. That gene comes up, and then I'm suddenly whisked away to another gene and have to go back to reselect what I want.

So, my preference would be that if you selected something you stay with it. If nothing is selected, we take you to the top variant. We don't want to forcing behaviour on the user. Also, if we decided that we would force you to start at the top variant, we should disable the ability to select things while loading since that just introduces confusion (but I don't think we should do that).

**Comment by WilliamRichards2017** [comment]
@AlistairNWard Sounds good, ill do it that way
