### ISSUE TITLE
Consistent focus on selected variant in left panel

### ISSUE THREAD

**Issue by WilliamRichards2017** [iobio/gene.iobio.vue#636]
Al's comment - "There isn't any focus in the left menu if you have selected a variant from it in gene in general. This might be worth adding though. If you select a variant from the left menu, there would be value in keeping an indicator in the left menu that the variant is selected. If you selected the variant in the main track, that would then also cause the variant to be highlighted in the left menu. "

**Comment by AlistairNWard** [comment]
Seems to be fixed
