### ISSUE TITLE
Support predefined gene sets

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio.vue#647]
We currently allow users to select the ACMG59 genes from the vertical elipsis attached to gene entry:

![Screen Shot 2020-10-22 at 11 50 25 AM](https://user-images.githubusercontent.com/523111/96897970-2af2c780-145d-11eb-9f7b-1c4a41c89735.png)

Extend this to allow a user to pick from multiple sets of genes:
1. The UI should be updated so instead of having a button for ACMG59, we have a scalable selection for multiple gene sets
2. We need somewhere to store these sets so we can easily add more sets and have them available through the UI

This is not a proposal to allow users to add their own sets of genes. We would manage the available sets.

**Comment by AlistairNWard** [comment]
Here are a couple of panels we could add (at Nebula's request):

**Cancer panel**
APC, ATM, AXIN2, BAP1, BARD1, BMPR1A, BRCA1, BRCA2, BRIP1, CDC73, CDH1, CDK4, CDKN2A, CHEK2, DICER1, EPCAM, FH, FLCN, GREM1, HOXB13, KIT, MAX, MEN1, MET, MITF, MLH1, MSH2, MSH3, MSH6, MUTYH, NBN, NF1, NF2, NTHL1, PALB2, PDGFRA, PMS2, POLD1, POLE, PRKAR1A, PTCH1, PTEN, RAD51C, RAD51D, RB1, RET, SDHA, SDHAF2, SDHB, SDHC, SDHD, SMAD4, SMARCA4, SMARCB1, STK11, TMEM127, TP53, TSC1, TSC2, VHL, WT1

**Cardio panel**
ACTA2, ACTC1, ACTN2, ACVRL1, APOB, BAG3, BMPR2, CACNA1C, CACNB2, CALM1, CALM2, CALM3, CASQ2, CAV1, CAV3, COL3A1, CRYAB, CSRP3, DES, DMD, DSC2, DSG2, DSP, EMD, ENG, F2, F5, F9, FBN1, FHL1, FLNC, GDF2, GLA, GPD1L, HCN4, JUP, KCNE1, KCNE2, KCNH2, KCNJ2, KCNQ1, LAMP2, LDLR, LDLRAP1, LMNA, MYBPC3, MYH11, MYH7, MYL2, MYL3, MYLK, NKX2-5, PCSK9, PKP2, PLN, PRKAG2, PRKG1, PROC, PROS1, RBM20, RYR2, SCN5A, SERPINC1, SGCD, SMAD3, SMAD4, TCAP, TGFB2, TGFB3, TGFBR1, TGFBR2, TMEM43, TNNC1, TNNI3, TNNT2, TPM1, VCL

**Comment by AlistairNWard** [comment]
We should address this sooner, rather than later.
1. This is a specific request from Nebula and it would be good to get the gene sets specified above available.
2. There will be an updated ACMG list in the near future, so we'll want to update this list. For useful archivability, it would be nice to have ACMG59 (or ACMG v2.0) as the current list still available, and then an updated ACMG v3.0 also available

**Comment by AlistairNWard** [comment]
When selecting the gene panel, we should probably indicate the cancer and cardio panel we have added are supplied by Nebula. The little tag that sits on the gene list is ok as just e.g. cardio, but in the dropdown, maybe list it as _Cardio panel (provided by Nebula Genomics_? I know there was concern that we don't want to be responsible for the contents of the panels, so as long as we specify an origin, I think we'd be safe

**Comment by tonydisera** [comment]
@AlistairNWard , I misunderstood.  So these 2 panels are Nebula specific?  Then I should add meta data regarding when the gene panel shows in the dropdown.  Thanks for noticing this.

**Comment by AlistairNWard** [comment]
They don't need to be Nebula specific, in that they can appear on prod gene.iobio. But there could be many cancer or cardio panels, so we should specify the origin of the panels we include. Marti could well ask for his own cardio panel of genes etc. and he'd need to be able to distinguish.

**Comment by tonydisera** [comment]
Cool.  Is there any value to allowing site specific gene panels?  I just added that functionality.

**Comment by AlistairNWard** [comment]
There probably is. If we get to a point where we are hosting lots of sets, this would probably be useful. But for now, it's probably ok to just make sure the name indicates the origin and make all panels available to everyone.

**Comment by AlistairNWard** [comment]
One minor typo. For the cardio panel, provided is missing a "d"

**Comment by tonydisera** [comment]
Oops!  Thanks for catching this @AlistairNWard !

**Comment by tonydisera** [comment]
Fixed.
