### ISSUE TITLE
gnomAD AF inconsistency

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio.vue#652]
Screenshot shows a variant with gnomAD AF of 0. The gnomAD browser (v3) shows 0.01752 for this variant:

https://gnomad.broadinstitute.org/variant/1-169549811-C-T?dataset=gnomad_r3

v2.1.1 (GRCh37) has different alleles, so I'm pretty sure we're looking at v3 here. But it also doesn't have AF of 0 anyway!

![screenshot compatibility issue](https://user-images.githubusercontent.com/523111/97616602-272dea80-19f3-11eb-8f6e-f6a7c0f762b3.png)

**Comment by tonydisera** [comment]
I have a fix for this that I am pushing with this release.  Anders will deploy the backend piece in the next week or so.

**Comment by tonydisera** [comment]
To test fix for GRCh38, use https://iobio.s3.amazonaws.com/samples/vcf/platinum-exome.GRCh38.vcf.gz.  When you click on RAI1, select the deletion.  You will see the gnomAD annotations for genomes.
<img width="146" alt="Screen Shot 2020-12-11 at 3 26 12 PM" src="https://user-images.githubusercontent.com/8420103/101960746-4bb9dc80-3bc5-11eb-8e2b-6e3dfa10124c.png">

For performance reasons, I decided to go back to 'on-demand' gnomAD annotations.  It speeds up 'analyze all' by 2x.  You will notice that when you click on the variant, it takes a few seconds for the annotation to show.  If you click on the ? by the 'Population frequency', it will indicate that for filtering, the gnomAD exomes pop max was used.

<img width="223" alt="Screen Shot 2020-12-11 at 3 26 17 PM" src="https://user-images.githubusercontent.com/8420103/101960760-53798100-3bc5-11eb-9aa6-4cf4736ac87b.png">
<img width="506" alt="Screen Shot 2020-12-11 at 3 26 25 PM" src="https://user-images.githubusercontent.com/8420103/101960764-570d0800-3bc5-11eb-87bc-31da6758452a.png">


This is less than ideal, but with Matt's slivar rework in annotateVariants, this should go away.

**Comment by AlistairNWard** [comment]
This fixes the incorrect AFs so is definitely good for now. There is a weird UI issue that I'm going to add separately though...
