### ISSUE TITLE
Parents tracks aren't available

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio.vue#653]
I'm testing some GRCh38 stuff using these links:

https://iobio.s3.amazonaws.com/samples/bam/NA12878.GRCh38.bam
https://iobio.s3.amazonaws.com/samples/bam/NA12891.GRCh38.bam
https://iobio.s3.amazonaws.com/samples/bam/NA12892.GRCh38.bam

https://iobio.s3.amazonaws.com/samples/vcf/platinum-exome.GRCh38.vcf.gz

And I put in gene F5. Proband track appears, but if I go on the Other Tracks dropdown, the only option is ClinVar. Why are the parents tracks not visible?

**Comment by adityaekawade** [comment]
Actually, even if you try entering the demo URL's in GRCH37, the mother and father tracks are not available.

https://s3.amazonaws.com/iobio/samples/bam/NA12878.exome.bam
https://s3.amazonaws.com/iobio/samples/bam/NA12892.exome.bam
https://s3.amazonaws.com/iobio/samples/bam/NA12891.exome.bam

https://s3.amazonaws.com/iobio/samples/vcf/platinum-exome.vcf.gz

The flags that are used to show these tracks are not being set. I will get a fix for this..

**Comment by adityaekawade** [comment]
@AlistairNWard  This is ready for testing on stage.gene

**Comment by AlistairNWard** [comment]
Remind me (and add to the deployment plan wiki page) whether I test on dev.gene or stage.gene. I keep forgetting!

**Comment by adityaekawade** [comment]
You test on stage.gene. Pull request linked to this issue was reviewed and merged on to the `dev` branch. With that, the staging version gets updated.  
However, If a developer wants quick feedback on an issue he can update the dev version ask you to test on dev.gene..

**Comment by AlistairNWard** [comment]
Why do we not see the coverage in the parents tracks? This is also important information, and I'm sure we used to see that.

**Comment by mvelinder** [comment]
I tested on stage.gene and got this? 
![image](https://user-images.githubusercontent.com/22081541/100282381-b8c44580-2f28-11eb-9671-b369feb879d6.png)

**Comment by AlistairNWard** [comment]
This is (almost) correct. When there are no variants present, having a
specific message stating that there are no variants makes it clear that the
empty track isn't a bug.

That said - why do we see the message twice for the proband?

Alistair Ward, PhD
Co-founder | President | COO
Frameshift Genomics Inc.

Director, Research and Science
Eccles Institute of Human Genetics
University of Utah School of Medicine

**Comment by adityaekawade** [comment]
I have fixed the message"No variants are present in proband" from appearing twice. You can try it on stage.gene 
![Screen Shot 2020-11-25 at 2 30 16 PM](https://user-images.githubusercontent.com/16284713/100289161-26727080-2f2d-11eb-8ef6-cb1daf8edd1e.png)

**Comment by AlistairNWard** [comment]
Looks good to me
