### ISSUE TITLE
Copy / paste gene list

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio.vue#660]
Comment from EIEE session:

Make it more obvious where to copy/paste gene list. The menu also disappears if I click outside of the overlay

**Comment by AlistairNWard** [comment]
The three vertical dots has been noted by Nebula users as not being obvious as well, so we should definitely make this clearer.

**Comment by adityaekawade** [comment]
I think we can replace the three vertical dots with a "copy" icon considering there is limited spacing available on the navbar. And, there is already a tooltip that indicates to add/ edit gene list. 
![Screen Shot 2020-11-16 at 11 49 56 AM](https://user-images.githubusercontent.com/16284713/99301015-32aa4f80-2802-11eb-99f5-b712a93e6765.png)

Also, the label for typeahead can say something like "Search gene" or "Select a gene" which will imply that the input field requires selecting a gene from typeahead.

**Comment by AlistairNWard** [comment]
I would say that we think about this in the context of #647. My guess is that changing the three dots to a different icon won't make it massively more obvious that is where you go to paste lists of genes. It also isn't obvious that there are predefined gene sets that you can go and select either.

So - and input from others would be good - I would propose that we replace the typeahead and three dots with a single button called "+ Add Genes" and then we rework the modal to have three sections:
1. A typeahead to add single genes. This would let you add multiple and build up a list
2. A dropdown of available predefined lists which would include ACMG59 and could then include those in #647 and be something we can grow
3. A freeform copy and paste area

I think this would provide a more comprehensive management of genes, and would be much clearer to the average user

**Comment by AlistairNWard** [comment]
Keep the typeahead on the menu bar as well.

**Comment by AlistairNWard** [comment]
Looks good to me.
