### ISSUE TITLE
Remove is_commercial flag

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio.vue#661]
Currently, there is an IS_COMMERCIAL flag in the .env file that, if set, removes things that we don't want to include in a commercial version. This currently turns off OMIM and Phenolyzer, but it is possible that we could want a version that has Phenolyzer, but not OMIM etc. Also, this flag is accessible to the customer, so they could manually turn this stuff on, which would be a problem in terms of licenses.

* Remove IS_COMMERCIAL flag
* Add individual settings to turn certain pieces off (OMIM and Phenolyzer for now)
* Put these flags somewhere where a customer can't flip the flag themselves

**Comment by tonydisera** [comment]
The latest Nebula gene.iobio is on https://dev.gene.iobio.io.  This .env has removed the IS_COMMERCIAL flag and added PHENOLYZER_PERMITTED=false.  To test, make sure that you don't see OMIM and you don't see 'enter phenotype' in the nav bar.  Try in simplified (default) and advanced mode

**Comment by AlistairNWard** [comment]
I don't see these in either mode, so assume fixed!
