### ISSUE TITLE
Remove upload data option in commercial version

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio.vue#662]
When launching gene from e.g. Nebula, or MyGene2, the data is automatically linked and the user should not be able to upload data. Apparently, the option being available has confused some Nebula users.

* Add a flag (see #661) to allow the upload data to be turned on/off for different instances
* If turned off, hide the option (![Screen Shot 2020-11-12 at 12 36 19 PM](https://user-images.githubusercontent.com/523111/98975306-f1552f80-24e3-11eb-937f-4706ba4399f1.png))

**Comment by AlistairNWard** [comment]
I still see the upload icon in the Nebula version

**Comment by tonydisera** [comment]
Hi Al.  Thanks for all of your testing!  In Gabor parlance, you are a brick and a dog.

Did you try on https://dev.gene.iobio.io?  I don't see the upload icon when I test there.

<img width="1317" alt="Screen Shot 2020-12-11 at 10 22 57 AM" src="https://user-images.githubusercontent.com/8420103/101934476-dfc27e80-3b9a-11eb-8a5f-a72ed8c4024e.png">

**Comment by tonydisera** [comment]
Oh shit.  I see it in Advanced mode.  Damn, you are good @AlistairNWard

**Comment by AlistairNWard** [comment]
Good old Gabor phrases! Is it a complement or an insult?! Who knows.

Yeah, I tested all the Nebula stuff on dev for both versions!

**Comment by tonydisera** [comment]
Okay, you can give it another try @AlistairNWard

**Comment by AlistairNWard** [comment]
Yep, all gone
