### ISSUE TITLE
Left panel can't be reopened

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio.vue#663]
You can x-out the left panel, and use the hamburger to reopen it. However, in the Nebula version, the hamburger isn't there, so if you close the left menu, you can't reopen it. Maybe we should get rid of the x and just rely on the hamburger to open/close the panel

**Comment by AlistairNWard** [comment]
I still see the x there

**Comment by adityaekawade** [comment]
Oh! This was fixed in commit # `bc691dc` but the IS_COMMERCIAL flag was removed after that, so you are still seeing it. I will fix this..

**Comment by adityaekawade** [comment]
You can test this on dev.gene.iobio.io 
![Screen Shot 2020-12-11 at 11 43 56 AM](https://user-images.githubusercontent.com/16284713/101948019-3c776680-3ba6-11eb-9f30-931aaf7791bb.png)

**Comment by AlistairNWard** [comment]
Fixed
