### ISSUE TITLE
Display coverage charts for Mother and Father tracks from variants tab?

### ISSUE THREAD

**Issue by adityaekawade** [iobio/gene.iobio.vue#668]
Coverage charts are not currently displayed for Mother and Father tracks when a gene is clicked from the "variant" tab.
![Screen Shot 2020-11-20 at 2 00 36 PM](https://user-images.githubusercontent.com/16284713/99858553-aae67d00-2b42-11eb-8787-b80c57c99dcc.png)

But they are shown when a gene is clicked from the "genes" tab on the left sidebar. 
![Screen Shot 2020-11-20 at 3 11 58 PM](https://user-images.githubusercontent.com/16284713/99858632-dbc6b200-2b42-11eb-9828-64712a0a0341.png)

**Comment by AlistairNWard** [comment]
@adityaekawade I just tried this and I see the coverage regardless of whether selecting from gene or variant. Can you confirm this is fixed (and close)?
