### ISSUE TITLE
Dynamic variant display

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio.vue#67]
Having analysed a gene list, it is obviously super cool to have them all appear at the left, but if the user selects a large gene list, they can be waiting for a while before having anything to look at.

When a gene analysis is completed, can any high priority variants appear at the left immediately rather than waiting till all genes are analysed?

If this was implemented, we would have to make it very clear that analysis was ongoing, and the available variant list is incomplete, but the user would then be able to start looking into those variants immediately.

As a follow on, it might then be nice to have a "viewed" status included next to each variant in the list at the left. If new variants get added as analysis proceeds, the variant order will shift, and the user would not want to forget which variants they have already looked at.

**Comment by mvelinder** [comment]
Not relevant anymore
