### ISSUE TITLE
Leave genome build unselected when loading custom URLs?

### ISSUE THREAD

**Issue by mvelinder** [iobio/gene.iobio.vue#679]
You can easily load grch38 bams and a vcf(s) in gene and forget to change the reference build drop down. And then you'll have very wrong analysis results - without any errors, just very weird and poor coverage in demo data. 

Found this while testing #653 and using these files
https://iobio.s3.amazonaws.com/samples/bam/NA12878.GRCh38.bam
https://iobio.s3.amazonaws.com/samples/bam/NA12891.GRCh38.bam
https://iobio.s3.amazonaws.com/samples/bam/NA12892.GRCh38.bam

https://iobio.s3.amazonaws.com/samples/vcf/platinum-exome.GRCh38.vcf.gz

**Comment by AlistairNWard** [comment]
The problem is being able to accurately detect which reference you have. It isn't always in the header, or you can find the reference file, but it might have a weird name. The VCF often has nothing at all to indicate the reference, but you could use contig lengths to determine. This is not necessarily trivial to check

**Comment by adityaekawade** [comment]
We can let the user select the build instead of selecting grch37 by default.

**Comment by AlistairNWard** [comment]
@adityaekawade - when launching from Mosaic, do you request the reference from the project?

**Comment by adityaekawade** [comment]
I will have to double-check this but I don't think we request the reference specifically but set the build from the query parameter of URL.

**Comment by mvelinder** [comment]
Al and I were just having this discussion and I landed with you @adityaekawade ! I think we should leave it unselected when loading their own data. And make the user select the build. We can provide links to resources for how to determine the build of their data. I'd like to force them to choose (correctly or incorrectly, given the information we provide them) rather than the silent errors of loading their data on grch37 by default and incorrectly analyzing it without any indication something might not be right. grch38 is becoming much more common and loading the grch38 platinum data with the links above and leaving grch37 as the build provides profoundly wrong and misleading views. 

grch38 data using grch37 build:
![image](https://user-images.githubusercontent.com/22081541/100286674-756dd500-2f30-11eb-96d0-3e687376ead3.png)

grch38 data using grch38 build: 
![image](https://user-images.githubusercontent.com/22081541/100286781-a0582900-2f30-11eb-8d1f-a5b2732982b5.png)

**Comment by adityaekawade** [comment]
Yeah, I had noticed that the analysis looks different when an incorrect build is selected. I think I was testing with the `F5` gene. But you can easily notice the issue that will be caused if an incorrect build is selected from the above example.

And I have just pushed a commit that should fix displaying the "no variants in proband" message twice.

**Comment by adityaekawade** [comment]
Ready for testing on https://stage.gene.iobio.io/

Genome build dropdown is left unselected when uploading custom data. You cannot click the "Load" button unless the build is selected. And to show that it is required, I have added the same "attention" css  class that is used in the app to show a required field. 

![Screen Shot 2020-12-07 at 10 47 52 AM](https://user-images.githubusercontent.com/16284713/101391836-c4453400-3879-11eb-96b6-9ac70b987841.png)

**Comment by mvelinder** [comment]
Looks good!

**Comment by AlistairNWard** [comment]
The genome build should be prepopulated for the demo data. If you open the data, then go to the files tab, you are forced to select the build, but we already know what it is for the demo data.

**Comment by adityaekawade** [comment]
> The genome build should be prepopulated for the demo data. If you open the data, then go to the files tab, you are forced to select the build, but we already know what it is for the demo data. Also, if you select the demo data from the dropdown in the file selection, it populates all the bam and vcf fields, but should also populate the reference as 37

Ready for testing on stage.gene.

**Comment by AlistairNWard** [comment]
Fixed
