### ISSUE TITLE
Demo data ACMG issues

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio.vue#68]
I just opened the demo data, then used the ACMG genes. Here are some observations that should maybe be broken into multiple issues (we could make this an epic and break into smaller issues as children of this, if you want to play with epics!)

1. I had an intermittent issue that is difficult to replicate, but I'll throw it in anyway. After all genes were analyzed, I clicked on one of the variants, and was told that no transcripts could be found for APOB and the variants were removed. I did get it back by entering APOB as a gene at the top.

2. In the left panel of variants, is there a better way of tying the variants to the gene? When there are multiple variants for a gene, it can get lost, and it wasn't immediately clear what gene a variant was in. Maybe this is containing the gene name in a slightly gray bar or something?

3. Click on an APOB variant from the list. The ranked variant table shows both variants from the list with a blue border, the selected one thicker. No real suggestions, but I'm not convinced this is the best way!

4. Still in APOB, the highest ranked variant (furthest left in the table), is not a high impact variant. This is because of the prioritization based on the hierarchy of rows in the table and the first variant has high allele frequency. This seems to have introduced a contradiction to me! If the table is prioritizing a variant, then the highest ranked in the gene should be the highest impact. Maybe we want to rethink this scheme?

**Comment by mvelinder** [comment]
Not relevant anymore
