### ISSUE TITLE
Stop analysis button no longer works

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio.vue#684]

**Comment by AlistairNWard** [comment]
Should the new icon be a solid square (for stop), rather than a pause symbol? Otherwise, this works now.

**Comment by tonydisera** [comment]
Good eye, @AlistairNWard.  Yeah, I think you are right.  I thought the pause button might be more recognizable to the general audience.

**Comment by tonydisera** [comment]
I changed this to the 'stop' glyph.  Good eye @AlistairNWard!

**Comment by AlistairNWard** [comment]
I just looked (on stage) and I just saw a gray circle with no symbol.

**Comment by tonydisera** [comment]
Hi @AlistairNWard .  Would you mind checking again?  It should look like this:

<img width="183" alt="Screen Shot 2020-12-28 at 7 38 12 PM" src="https://user-images.githubusercontent.com/8420103/103254875-5d7cdd00-4944-11eb-8e33-3181a2862441.png">

**Comment by AlistairNWard** [comment]
Now we can add movies!

https://user-images.githubusercontent.com/523111/103294120-33b4cc00-49bf-11eb-8ca4-3c54619475a6.mov

**Comment by AlistairNWard** [comment]
I also cleared out my cache, just in case, but I still just see a gray circle.

![Screen Shot 2020-12-29 at 10 19 10 AM](https://user-images.githubusercontent.com/523111/103294220-66f75b00-49bf-11eb-903e-e5b722cf2a6f.png)

**Comment by tonydisera** [comment]
This is so strange, @AlistairNWard.  How in the world could we show different glyphs?  I tried in Firefox and Chrome.  What browser are you running in?

**Comment by tonydisera** [comment]
This leaves me weary.  I am going to change back to the original glyph.  Now if you tell me you see a smiley face, I'm quitting.

**Comment by tonydisera** [comment]
Does it look like this now @AlistairNWard?  
![Uploading Screen Shot 2020-12-29 at 1.08.26 PM.png…]()

**Comment by AlistairNWard** [comment]
Yes, now I see it as just the square.

**Comment by tonydisera** [comment]
@AlistairNWard sees a square.  Tonight, I sleep well.

**Comment by AlistairNWard** [comment]
I take my role as bringer of bad news seriously!
