### ISSUE TITLE
gene.iobio needs to go on a diet

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio.vue#686]
The current production build is ~ 17MB.  We can probably get rid of the bam.js local file libraries.

<img width="932" alt="Screen Shot 2020-11-30 at 1 41 25 PM" src="https://user-images.githubusercontent.com/8420103/100663412-78433e00-3313-11eb-8fa3-042378c451c6.png">

And a few rather large .pngs

But the real work will be looking at our dependencies:

https://www.google.com/search?q=webpack+analyzer&oq=webpack+analyzer&aqs=chrome..69i57j0l6.2255j0j7&sourceid=chrome&ie=UTF-8

**Comment by AlistairNWard** [comment]
This will come up again if still a problem as we reenigineer
