### ISSUE TITLE
No scale on parent tracks

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio.vue#687]
I launched BRCA1 for project 400 (https://mosaic.chpc.utah.edu/#/projects/400/samples) for the top sample (DK0107945). There are no variants for the proband. Select the parent tracks and I get the following:

![Screen Shot 2020-12-07 at 1 24 32 PM](https://user-images.githubusercontent.com/523111/101389659-c31f0180-388f-11eb-995d-93cb20201325.png)

No coverage information or scale. Click the gene name in the left panel and it loads:

![Screen Shot 2020-12-07 at 1 26 24 PM](https://user-images.githubusercontent.com/523111/101389749-e053d000-388f-11eb-9c36-4def9f1f6728.png)

**Comment by AlistairNWard** [comment]
@adityaekawade can you confirm this is fixed (it appears to be) and close?

**Comment by adityaekawade** [comment]
I can see the scale for parents track without having to click the gene name in the left panel. Seems to be fixed.
