### ISSUE TITLE
Update genomebuild db to point clinvar to ftp site

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio.vue#69]

**Comment by mvelinder** [comment]
I think this work has been done, yes @tonydisera and @anderspitman ?

**Comment by anderspitman** [comment]
Maybe I'm confused about what this means, but it seems like the opposite of what we want. We want to minimize the number of requests our apps make to domains we don't control.

**Comment by AlistairNWard** [comment]
I assume this is to do with periodically downloading the newest clinvar vcf. Regardless, it's so old that it'll be covered by other issues
