### ISSUE TITLE
HGVS fails for non-proband variants

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio.vue#690]
I opened the demo data set, view the parental tracks, then select a variant in a parent, but NOT present in the proband. I always get the following error:

![Screen Shot 2020-12-11 at 11 48 36 AM](https://user-images.githubusercontent.com/523111/101930982-d93a0400-3ba6-11eb-8c2d-be9cffea2966.png)

**Comment by AlistairNWard** [comment]
@adityaekawade has this been fixed? I can't replicate. If it is fixed, or you also can't replicate (just use any gene where the parents have variants the proband doesn't), you can close this issue.

**Comment by adityaekawade** [comment]
Tried with different genes, selecting variants in the parent that are not present in the proband. I couldn't replicate it and didn't get the error. Closing it.
