### ISSUE TITLE
Load icon when generating gnomAD AF

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio.vue#694]
If you select a new variant, the gnomAD AF has a question mark, and then changes when it is found. It makes it look as though the AF is unknown, rather than being loaded. I've attached a movie to Slack

**Comment by AlistairNWard** [comment]
If I try this now, I see loading more annotations which is good, but there is still a gnomAD annotation shown while this loads. It seems to usually be 0% and then once the annotation is loaded it changes to the correct value. We shouldn't show a gnomAD AF while it is being loaded

**Comment by tonydisera** [comment]
Hi Al.  This is the drawback to using the gnomAD exomes for the "analyze all" processing and then using gnomAD genomes "on-demand" when the variant is selected.  What variant did you notice it going from 0% to another frequency?  Click on the ? in the 'Population frequency' header, and it should tell you the frequency used from exomes for filtering purposes.

<img width="217" alt="Screen Shot 2020-12-18 at 2 42 34 PM" src="https://user-images.githubusercontent.com/8420103/102664097-51706e80-413f-11eb-8024-2ff9dddc4962.png">
<img width="510" alt="Screen Shot 2020-12-18 at 2 42 27 PM" src="https://user-images.githubusercontent.com/8420103/102664195-782ea500-413f-11eb-963c-1b494322f743.png">

This is less than ideal, but the "analyze all" finishes in about half of the time if we filter first by gnomAD exomes (from VEP) and then do on-demand gnomAD genome annotations for the selected variant.  Perhaps we should discuss ways to make this less confusing to the user. For example, perhaps the AF shouldn't show in the Variant detail card until the gnomAD genome annotations are retreived.

**Comment by AlistairNWard** [comment]
I've added a video to Slack. You'll see when I click on the first variant, I have the red icon with 0%, then the annotations load and it changes to gray and 37%. Then I click on another variant, the icon goes back to the red one with 0% and a loading annotations glyph. When the loading finishes, it again changes to gray with 77% AF. When the annotation is loading, there should be no AF visible, since we don't know it yet.

**Comment by tonydisera** [comment]
Thank you.  I will look into this.  I suspect that the AF was filled in on the VCF, which should be ignored.

**Comment by tonydisera** [comment]
Excellent testing @AlistairNWard, as always.  Thank you!  Yeah, you uncovered a problem with the 'on-demand' gnomAD annotations.  I've fixed the code and you can verify on https://stage.gene.iobio.io.  Thanks for the screencast!

**Comment by AlistairNWard** [comment]
Thanks @tonydisera . This seems to be fixed, but is very slow in some cases. I went to AIRE for the demo data, and click on any variant. The gnomAD exomes comes in immediately, but the loading more annotations never completes. Are there actually no more annotations and this shouldn't show?

**Comment by tonydisera** [comment]
Hi @AlistairNWard.  I did change the behavior so that we only get the gnomAD genome annotations on-demand.  However, it should always return.  I can't seem to reproduce this particular problem.  When there are no annotations, the loading.. gif should go away and the AF should remain the value it was (from the gnomAD exomes MAX AF).  I wonder if this was a network issue.  Regardless, it is less than optimal.  Right now, until we can speed up the 'annotate variants' script, we have to choose between better response times for 'Analyze all' vs response when a variant is selected.  This would be a good discussion for our next IOBIO meeting.

**Comment by AlistairNWard** [comment]
I tried to recreate on AIRE this morning and things seem to be loading, so we'll call this fixed. That seems like a sensible discussion topic though
