### ISSUE TITLE
Switching between Gencode and RefSeq doesn't work for previously selected gene

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio.vue#703]

**Comment by AlistairNWard** [comment]
I'm not totally sure what this means. Is this that if I change to RefSeq and then change to a different gene, it is still on GenCode? If so, that no longer happens. I noticed a couple of things though,

1. If I change to RefSeq, all genes need to be reanalyzed, but this isn't automatically triggered. Probably should be
2. Some of the transcripts now say null next to them

![Screen Shot 2020-12-18 at 12 30 07 PM](https://user-images.githubusercontent.com/523111/102643131-d0a87700-412c-11eb-9b4a-24581344003c.png)

**Comment by tonydisera** [comment]
Interesting.  I'm glad you caught this oddity.  I'll look into why the labels are missing.  I was probably a bit overzealous in clearing out cached elements when the source changes, which requires a complete reload of the data.  That is a good point about kicking off 'analyze all'.  I'll do that as well.  Thank you!!

**Comment by tonydisera** [comment]
Thanks for your thoroughness @AlistairNWard.  Nothing slips by you! 
1.  Yes, the behavior is that if you switch to RefSeq (or vice versa) all genes will be re-analyzed with the new transcript source.
2. I fixed the null label showing up to the right of the transcript for RefSeq.
3. Analyze all will be kicked off with the gene source changes.

**Comment by AlistairNWard** [comment]
Fixed
