### ISSUE TITLE
Remove extraneous backend requests that occur when selecting a variant

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio.vue#705]
There are duplicate requests made to the NCBI eutils and iobio gru backend when a variant is selected.
<img width="729" alt="Screen Shot 2020-12-15 at 8 13 21 PM" src="https://user-images.githubusercontent.com/8420103/102300422-26ed9e00-3f12-11eb-86f1-dec7a58f3754.png">

**Comment by AlistairNWard** [comment]
Not sure how to test this. I selected the RAI1 variant in prod gene and in stage, and see the same network activity:

![Screen Shot 2020-12-18 at 12 34 51 PM](https://user-images.githubusercontent.com/523111/102643630-8a074c80-412d-11eb-9e1b-102afced2a87.png)

![Screen Shot 2020-12-18 at 12 34 57 PM](https://user-images.githubusercontent.com/523111/102643632-8a074c80-412d-11eb-9561-07d478cdbcc3.png)

**Comment by tonydisera** [comment]
Yes, this is a tricky one.  It turns out that 'annotateVariants' was called twice.  The phylop and sequence requests are fine; the first requests return 204 and then the second return 200, which (I think) means that the scores and multi-way seq alignments were server-side cached.  So to verify this works, just make sure that you only see one 'annotateVariants' request after you select a variant.

**Comment by AlistairNWard** [comment]
Makes sense. I do only see 1 annotateVariants, and 2 in prod gene
