### ISSUE TITLE
The circle around the selected variant (and the coverage marker) go away after variant is selected

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio.vue#706]
I noticed that after I clicked on a filtered variant in the left panel, the variant would be circled in the Variants card, but then after a few seconds, the circle (and the coverage dot and label) would go away.

It turns out that the fix #648 to rescale the y-axis on zoom for the coverage chart was not scoping the d3 select properly and was also using a timeout, which caused the hide to occur after the variant had been circled.

**Comment by AlistairNWard** [comment]
I've seen this as well.
