### ISSUE TITLE
Multi-align sequence incorrect for variants on reverse-strand genes

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio.vue#707]
For reverse-strand genes (MTHFR is an example), the muti-way sequence never seemed to correspond to the reference.  It turns out that the fasta files for multi-way align should be parsed from the end of the sequence to the beginning.

**Comment by tonydisera** [comment]
The best way to test this is to see how it is broken on production first.  So pull up the demo dataset for gene BRCA1.  You will notice that the multi-way align sequence for Human at the variant position doesn't match the reverse complement of the ref in the variant.
<img width="567" alt="Screen Shot 2020-12-17 at 1 46 50 PM" src="https://user-images.githubusercontent.com/8420103/102542446-0be47080-406f-11eb-86e0-670a50d661aa.png">

If you try this on stage for this same variant, you will see that the multi-way align should show the same base for Human as what is indicated in the 'ref' of the variant.  Since the multi-way align show in reverse strand orientation for those genes transcribed on the reverse strand, I have change the ref->alt label into this same reverse complement form.
![Uploading Screen Shot 2020-12-17 at 1.43.59 PM.png…]()

**Comment by AlistairNWard** [comment]
Yep, this works.
