### ISSUE TITLE
Update software and resource versions on 'About' page

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio.vue#711]
<img width="609" alt="Screen Shot 2020-12-29 at 4 34 28 PM" src="https://user-images.githubusercontent.com/8420103/103320732-cd966c00-49f3-11eb-8c78-76e096d4c4f3.png">

@anderspitman, do you happen to know what version of VEP, samtools, bcftools, and tabix are we using?  Or is there a config file in iobio gru backend that I can reference?  Thanks!

**Comment by anderspitman** [comment]
AWS is on VEP 101, but unfortunately Utah Mosaic is still 97, so it's not consistent. Hopefully I'll be able to get Mosaic up to 101 soon, but I'll also be changing both of them to 103 as soon as that's ready, since it fixes some upstream VEP bugs.

**Comment by tonydisera** [comment]
Thank you @anderspitman!  Are we only the latest versions of samtools and tabix?

**Comment by tonydisera** [comment]
@anderspitman, do you happen to know the versions for the following?

Freebayes
samtools
tabix
vt

Thank you!
Tony

**Comment by tonydisera** [comment]
@adityaekawade , do you happen to know the version of Phenolyzer we are running?

Thanks,
Tony

**Comment by adityaekawade** [comment]
I think @anderspitman had updated the Phenolyzer to the latest version when he moved it to the new backend. Their latest release (October 2019) on GitHub shows version 0.4.0

**Comment by anderspitman** [comment]
Sure thing:

Freebayes: v1.3.1
samtools: 1.9
tabix: 1.9
vt: v0.57721

**Comment by tonydisera** [comment]
Thank you @anderspitman !!!

**Comment by tonydisera** [comment]
Thank you @adityaekawade !!

**Comment by mvelinder** [comment]
Looks completed to me!
