### ISSUE TITLE
For Files dialog, when tbi is in separate url, don't try to access vcf until tbi URL is entered

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio.vue#712]

**Comment by stefinfection** [comment]
I can't reproduce this on dev branch or production - @AlistairNWard can you double check that it's also not happening for you?

**Comment by adityaekawade** [comment]
I just tried this: Separate URL for tbi > entered VCF URL > waited for a couple of minutes > entered tbi URL . It worked and there were no errors. Earlier it used to show errors in the console, so looks like it is fixed.

**Comment by AlistairNWard** [comment]
Agreed, looks like it's fixed.
