### ISSUE TITLE
Why is Safari shown as not supported?

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio.vue#713]
From @AlistairNWard - 
Have we explicitly disabled gene from working on Safari? I was testing some of the issues on Chrome and Firefox, but when I tried Safari, we just provide a warning that only Chrome and Firefox are supported. Do we know there are problems on Safari?

**Comment by mvelinder** [comment]
I don't know of specific problems with Safari. We might just prompt that we highly recommend Chrome and cannot guarantee your experience in Safari. But still allow them to actually use it on Safari.
