### ISSUE TITLE
Coverage chart in Variant detail clips at half exon

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio.vue#719]
<img width="179" alt="Screen Shot 2021-02-08 at 3 20 39 PM" src="https://user-images.githubusercontent.com/8420103/107288971-8b643f80-6a21-11eb-8b42-99dec836b267.png">

**Comment by AlistairNWard** [comment]
I'm not seeing this anymore, and it is also mentioned in a different issue.
