### ISSUE TITLE
Where are REVEL scores

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio.vue#722]
On a recent project, Marti created a clin analysis and created a filter for missense variants with REVEL 0.75. Two variants are returned, but there is no REVEL score in the variant review panel.

<img width="1680" alt="Screen Shot 2021-03-07 at 4 41 51 PM" src="https://user-images.githubusercontent.com/523111/110255883-0ad32900-7f64-11eb-8d40-25c24a8681c7.png">

This can be accessed from Marti's saved analysis:

https://mosaic.chpc.utah.edu/#/projects/191/analyses

**Comment by tonydisera** [comment]
The code was trying to accommodate a REVEL filter along with other filters.  So it was treating variants without a REVEL score as ‘passing’ the filter.  The fix will make the REVEL filter restrictive to missense variants and warn the user as such.  There was also another bug that was limiting the search to only those variants not captured by our standard filters.  I am removing that limitation as well.

**Comment by tonydisera** [comment]
emergency bug fix 4.4.4.3
