### ISSUE TITLE
Make Phenolyzer available in simplified view (Nebula)

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio.vue#726]
It is currently only visible in the Advanced view

**Comment by adityaekawade** [comment]
I have addressed this issue in a recent commit. How do we deploy it to Nebula?

**Comment by AlistairNWard** [comment]
I can coordinate with Nebula to update their version. We'll get them to update when the analytics is updated to not include the urls and when #727 is also fixed.

Remember to move issues that are being worked on into the current sprint, so we know what is actually in progress and what is in planning waiting to move across for work.
