### ISSUE TITLE
Saving 300 plus variants fails

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio.vue#749]
Go to MUC3A from Nebula. There are loads of missense variants, but trying to save them fails.

**Comment by AlistairNWard** [comment]
We should do some comprehensive testing of saving. We've had a couple of reports of failure to export. Couple of observations:

- [ ] Go to MUC3A from Nebula, then go to advanced view and save and it fails. This is probably a volume issue, but we should handle it
- [ ] Save variants from demo. Once the save is complete, the save modal is still open. This should close automatically

**Comment by tonydisera** [comment]
This system load is caused b/c the app is re-annotating each variant to get the 'extra' annotations for HGVSp and HGVSc, which is an expensive VEP call.  Right now, I've worked around the problem by only filling in these extra annotations if we have less than 50 variants we are exporting.  If there are more than 50, the app does not do the extra annotation, but instead exports the variants without the HGVSp and HGVSc columns filled in. 

The warning message is: "More than 50 variants are being exported. To prevent high system load, the HGVSc and HGVCp annotations will not be provided in the export file."

**Comment by AlistairNWard** [comment]
This seems like a good interim solution
