### ISSUE TITLE
Use genome build GRCh38 for platinum demo dataset 

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio.vue#750]

**Comment by AlistairNWard** [comment]
AWS URLs for updated demo data can be found on Mosaic. This is the collection that has the links to the 4 projects (GRCh37 and 38, exomes and genomes): https://mosaic.chpc.utah.edu/#/collections/484/projects/

If we want to use GRCh38 exomes, that's this project (https://mosaic.chpc.utah.edu/#/projects/478/) and the AWS URLs are on the dashboard
