### ISSUE TITLE
Warning on gene limit

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio.vue#751]
Include a very clear, concise message where users can paste lists of genes that they should limit themselves to less than 50 genes. Maybe text like "Please limit the number of genes to less than 50"

**Comment by AlistairNWard** [comment]
I was thinking that the warning would be always present. E.g. you open the modal and there is always text recommending less than 50 genes should be entered.

**Comment by stefinfection** [comment]
Updated to 'Enter gene names (<50 recommended)'. Also wanted to document here that it's a little counterintuitive to suggest <50 gene names when the provided lists are between 59-77 genes, but after discussing with @AlistairNWard we decided to keep the warning at 50, and the hard limit at 200.
