### ISSUE TITLE
Numbers too large

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio.vue#753]
If a gene has too many variants, the number doesn't fit inside the circle and it's illegible

![Screen Shot 2021-08-03 at 7 59 59 PM](https://user-images.githubusercontent.com/523111/128101205-2657b20b-b4b8-40f8-a03d-2321881635d1.png)

**Comment by adityaekawade** [comment]
What's the maximum digits this badge should handle? Can it have a 4 digit number? @AlistairNWard

**Comment by AlistairNWard** [comment]
I think 3 should be enough. If we’re pulling in thousands of variants into a gene, we’ll have other problems!
