### ISSUE TITLE
Make Call Variants functionality more obvious

### ISSUE THREAD

**Issue by mvelinder** [iobio/gene.iobio.vue#754]
Currently it is only within the Genes tab of the left panel. But users spend most of their time in the Variants tab. I'd suggest we add these buttons to the Variants tab as well, or move them somewhere outside of the left panel where they can be seen. 

![image](https://user-images.githubusercontent.com/22081541/128201758-e7123f4f-9f3c-486c-b81d-ae3350a3f85f.png)

**Comment by AlistairNWard** [comment]
Clone call variants button on variants tab
