### ISSUE TITLE
Set AF filter

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio.vue#759]
In the filter, the entry field has % as the unit, but it's not a %, it's AF - e.g. 0.01, not 1%. We should be clearer

![Screen Shot 2021-08-04 at 3 32 53 PM](https://user-images.githubusercontent.com/523111/128243633-503c83e4-4f01-430f-be2f-f4c220d93321.png)

**Comment by AlistairNWard** [comment]
Make sure everywhere in the app we use AF not percentage.

**Comment by mvelinder** [comment]
Also confirm that filtering is working on 0.01 as 1% and NOT 1%... like we discussed just now

**Comment by mvelinder** [comment]
Make everything be frequency throughout. Not percentage.

**Comment by stefinfection** [comment]
Went with .3n formatting for decimal display - happy to change to another value if preferred

**Comment by AlistairNWard** [comment]
.3n is 3 digits with 2 after the decimal place, right? So 0.01 would be viewable, but 0.001 would be shown as 0.00? Since 0.001 is 0.1%, which isn't outrageous, maybe .4n would be better? Or is it possible to switch to scientific notation if < 0.01?
